//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\com\ashera\spatialkit\CompassManager.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CompassManager")
#ifdef RESTRICT_CompassManager
#define INCLUDE_ALL_CompassManager 0
#else
#define INCLUDE_ALL_CompassManager 1
#endif
#undef RESTRICT_CompassManager

#if !defined (ASCompassManager_) && (INCLUDE_ALL_CompassManager || defined(INCLUDE_ASCompassManager))
#define ASCompassManager_

#define RESTRICT_IFragmentManager 1
#define INCLUDE_ASIFragmentManager 1
#include "IFragmentManager.h"

@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;
@protocol JavaUtilMap;

@interface ASCompassManager : NSObject < ASIFragmentManager >

#pragma mark Public

- (instancetype)init;

- (id<ASIFragmentManager>)newInstance OBJC_METHOD_FAMILY_NONE;

- (void)onAttachWithASIFragment:(id<ASIFragment>)fragment;

- (void)onCreateWithASIFragment:(id<ASIFragment>)fragment
              withNSObjectArray:(IOSObjectArray *)args;

- (void)onDestroyWithASIFragment:(id<ASIFragment>)fragment;

- (void)onDetachWithASIFragment:(id<ASIFragment>)fragment;

- (void)onPauseWithASIFragment:(id<ASIFragment>)fragment;

- (void)onRequestPermissionsResultWithASIFragment:(id<ASIFragment>)fragment
                                          withInt:(int32_t)requestCode
                                withNSStringArray:(IOSObjectArray *)permissions
                                     withIntArray:(IOSIntArray *)grantResults;

- (void)onResumeWithASIFragment:(id<ASIFragment>)fragment;

- (void)onSaveInstanceStateWithASIFragment:(id<ASIFragment>)fragment
                         withNSObjectArray:(IOSObjectArray *)args;

- (void)onStartWithASIFragment:(id<ASIFragment>)fragment;

- (void)onStopWithASIFragment:(id<ASIFragment>)fragment;

- (void)sendEventWithNSString:(NSString *)action
              withJavaUtilMap:(id<JavaUtilMap>)extraData;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(ASCompassManager)

FOUNDATION_EXPORT void ASCompassManager_init(ASCompassManager *self);

FOUNDATION_EXPORT ASCompassManager *new_ASCompassManager_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCompassManager *create_ASCompassManager_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCompassManager)

@compatibility_alias ComAsheraSpatialkitCompassManager ASCompassManager;


#endif

#pragma pop_macro("INCLUDE_ALL_CompassManager")
