//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\com\ashera\spatialkit\CompassViewImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CompassViewImpl")
#ifdef RESTRICT_CompassViewImpl
#define INCLUDE_ALL_CompassViewImpl 0
#else
#define INCLUDE_ALL_CompassViewImpl 1
#endif
#undef RESTRICT_CompassViewImpl

#if !defined (ASCompassViewImpl_) && (INCLUDE_ALL_CompassViewImpl || defined(INCLUDE_ASCompassViewImpl))
#define ASCompassViewImpl_

#define RESTRICT_IAttributable 1
#define INCLUDE_ASIAttributable 1
#include "IAttributable.h"

@class ASWidgetAttribute;
@class NSString;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;

@interface ASCompassViewImpl : NSObject < ASIAttributable >

#pragma mark Public

- (instancetype)init;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (NSString *)getLocalName;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id<ASIAttributable>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCompassViewImpl)

inline NSString *ASCompassViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCompassViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCompassViewImpl, LOCAL_NAME, NSString *)

FOUNDATION_EXPORT void ASCompassViewImpl_init(ASCompassViewImpl *self);

FOUNDATION_EXPORT ASCompassViewImpl *new_ASCompassViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCompassViewImpl *create_ASCompassViewImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCompassViewImpl)

@compatibility_alias ComAsheraSpatialkitCompassViewImpl ASCompassViewImpl;


#endif

#pragma pop_macro("INCLUDE_ALL_CompassViewImpl")
