//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\com\ashera\spatialkit\CompassManager.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "CompassHelper.h"
#include "CompassManager.h"
#include "EventBus.h"
#include "IFragment.h"
#include "IFragmentManager.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "java/lang/Double.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/lang/Math.h"
#include "java/util/HashMap.h"
#include "java/util/Map.h"

#import <CoreLocation/CoreLocation.h>




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface ASCompassManager () {
 @public
  id<ASIFragment> fragment_;
  float heading_;
  float oldHeading_;
  float longitude_;
  float latitude_;
  float altitude_;
  float magneticDeclination_;
  float trueHeading_;
  float oldTrueHeading_;
  bool stopListeners_;
  id locationManager_;
}

- (void)removeListeners;

- (void)removeAndStopListeners;

- (void)startNative;

- (void)stopNative;

- (void)onHeadingUpdateWithDouble:(double)magnetic
                       withDouble:(double)trueHeadingVal
                       withDouble:(double)accuracy
                       withDouble:(double)lat
                       withDouble:(double)lng
                       withDouble:(double)alt;

- (double)adjustForWrapWithDouble:(double)newHeading
                       withDouble:(double)currentHeading;

- (double)smoothHeadingWithDouble:(double)newHeading
                       withDouble:(double)currentHeading;

- (void)onError;

- (void)publishResult;

@end

J2OBJC_FIELD_SETTER(ASCompassManager, fragment_, id<ASIFragment>)
J2OBJC_FIELD_SETTER(ASCompassManager, locationManager_, id)

__attribute__((unused)) static void ASCompassManager_removeListeners(ASCompassManager *self);

__attribute__((unused)) static void ASCompassManager_removeAndStopListeners(ASCompassManager *self);

__attribute__((unused)) static void ASCompassManager_startNative(ASCompassManager *self);

__attribute__((unused)) static void ASCompassManager_stopNative(ASCompassManager *self);

__attribute__((unused)) static void ASCompassManager_onHeadingUpdateWithDouble_withDouble_withDouble_withDouble_withDouble_withDouble_(ASCompassManager *self, double magnetic, double trueHeadingVal, double accuracy, double lat, double lng, double alt);

__attribute__((unused)) static double ASCompassManager_adjustForWrapWithDouble_withDouble_(ASCompassManager *self, double newHeading, double currentHeading);

__attribute__((unused)) static double ASCompassManager_smoothHeadingWithDouble_withDouble_(ASCompassManager *self, double newHeading, double currentHeading);

__attribute__((unused)) static void ASCompassManager_onError(ASCompassManager *self);

__attribute__((unused)) static void ASCompassManager_publishResult(ASCompassManager *self);

@implementation ASCompassManager

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCompassManager_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)onCreateWithASIFragment:(id<ASIFragment>)fragment
              withNSObjectArray:(IOSObjectArray *)args {
  self->fragment_ = fragment;
  heading_ = oldHeading_ = longitude_ = latitude_ = altitude_ = magneticDeclination_ = trueHeading_ = 0;
}

- (void)onResumeWithASIFragment:(id<ASIFragment>)fragment {
  if (!stopListeners_) {
    ASCompassManager_startNative(self);
  }
}

- (void)onPauseWithASIFragment:(id<ASIFragment>)fragment {
  ASCompassManager_removeListeners(self);
}

- (void)removeListeners {
  ASCompassManager_removeListeners(self);
}

- (void)removeAndStopListeners {
  ASCompassManager_removeAndStopListeners(self);
}

- (void)startNative {
  ASCompassManager_startNative(self);
}

- (void)stopNative {
  ASCompassManager_stopNative(self);
}

- (void)onHeadingUpdateWithDouble:(double)magnetic
                       withDouble:(double)trueHeadingVal
                       withDouble:(double)accuracy
                       withDouble:(double)lat
                       withDouble:(double)lng
                       withDouble:(double)alt {
  ASCompassManager_onHeadingUpdateWithDouble_withDouble_withDouble_withDouble_withDouble_withDouble_(self, magnetic, trueHeadingVal, accuracy, lat, lng, alt);
}

- (double)adjustForWrapWithDouble:(double)newHeading
                       withDouble:(double)currentHeading {
  return ASCompassManager_adjustForWrapWithDouble_withDouble_(self, newHeading, currentHeading);
}

- (double)smoothHeadingWithDouble:(double)newHeading
                       withDouble:(double)currentHeading {
  return ASCompassManager_smoothHeadingWithDouble_withDouble_(self, newHeading, currentHeading);
}

- (void)onError {
  ASCompassManager_onError(self);
}

- (void)publishResult {
  ASCompassManager_publishResult(self);
}

// Location updates
- (void)locationManager:(CLLocationManager *)manager
didUpdateLocations:(NSArray<CLLocation *> *)locations
{
  CLLocation *loc = [locations lastObject];
  if (loc) {
    double lat = loc.coordinate.latitude;
    double lng = loc.coordinate.longitude;
    double alt = loc.altitude;
    
    objc_setAssociatedObject(self, "lat", @(lat), OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    objc_setAssociatedObject(self, "lng", @(lng), OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    objc_setAssociatedObject(self, "alt", @(alt), OBJC_ASSOCIATION_RETAIN_NONATOMIC);
  }
}

// Heading updates
- (void)locationManager:(CLLocationManager *)manager
didUpdateHeading:(CLHeading *)heading
{
  double magnetic = heading.magneticHeading;
  double trueHeadingVal = heading.trueHeading;
  double accuracy = heading.headingAccuracy;
  
  NSNumber *latNum = objc_getAssociatedObject(self, "lat");
  NSNumber *lngNum = objc_getAssociatedObject(self, "lng");
  NSNumber *altNum = objc_getAssociatedObject(self, "alt");
  
  double lat = latNum ? [latNum doubleValue] : 0;
  double lng = lngNum ? [lngNum doubleValue] : 0;
  double alt = altNum ? [altNum doubleValue] : 0;
  
  [self onHeadingUpdateWithDouble:magnetic
  withDouble:trueHeadingVal
  withDouble:accuracy
  withDouble:lat
  withDouble:lng
  withDouble:alt];
}

- (void)locationManager:(CLLocationManager *)manager
didFailWithError:(NSError *)error
{
  [self onError];
}

- (BOOL)locationManagerShouldDisplayHeadingCalibration:(CLLocationManager *)manager
{
  return YES;
}

- (void)onDestroyWithASIFragment:(id<ASIFragment>)fragment {
  ASCompassManager_stopNative(self);
}

- (id<ASIFragmentManager>)newInstance {
  return new_ASCompassManager_init();
}

- (void)sendEventWithNSString:(NSString *)action
              withJavaUtilMap:(id<JavaUtilMap>)extraData {
  switch (JreIndexOfStr(action, (id[]){ @"onDestinationReached" }, 1)) {
    case 0:
    ASCompassManager_removeAndStopListeners(self);
    break;
  }
}

- (void)onAttachWithASIFragment:(id<ASIFragment>)fragment {
}

- (void)onDetachWithASIFragment:(id<ASIFragment>)fragment {
}

- (void)onRequestPermissionsResultWithASIFragment:(id<ASIFragment>)fragment
                                          withInt:(int32_t)requestCode
                                withNSStringArray:(IOSObjectArray *)permissions
                                     withIntArray:(IOSIntArray *)grantResults {
}

- (void)onSaveInstanceStateWithASIFragment:(id<ASIFragment>)fragment
                         withNSObjectArray:(IOSObjectArray *)args {
}

- (void)onStartWithASIFragment:(id<ASIFragment>)fragment {
}

- (void)onStopWithASIFragment:(id<ASIFragment>)fragment {
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 5, 6, -1, -1, -1, -1 },
    { NULL, "D", 0x2, 7, 8, -1, -1, -1, -1 },
    { NULL, "D", 0x2, 9, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 3, -1, -1, -1, -1 },
    { NULL, "LASIFragmentManager;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 11, 12, -1, 13, -1, -1 },
    { NULL, "V", 0x1, 14, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 15, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 18, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 19, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 3, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(onCreateWithASIFragment:withNSObjectArray:);
  methods[2].selector = @selector(onResumeWithASIFragment:);
  methods[3].selector = @selector(onPauseWithASIFragment:);
  methods[4].selector = @selector(removeListeners);
  methods[5].selector = @selector(removeAndStopListeners);
  methods[6].selector = @selector(startNative);
  methods[7].selector = @selector(stopNative);
  methods[8].selector = @selector(onHeadingUpdateWithDouble:withDouble:withDouble:withDouble:withDouble:withDouble:);
  methods[9].selector = @selector(adjustForWrapWithDouble:withDouble:);
  methods[10].selector = @selector(smoothHeadingWithDouble:withDouble:);
  methods[11].selector = @selector(onError);
  methods[12].selector = @selector(publishResult);
  methods[13].selector = @selector(onDestroyWithASIFragment:);
  methods[14].selector = @selector(newInstance);
  methods[15].selector = @selector(sendEventWithNSString:withJavaUtilMap:);
  methods[16].selector = @selector(onAttachWithASIFragment:);
  methods[17].selector = @selector(onDetachWithASIFragment:);
  methods[18].selector = @selector(onRequestPermissionsResultWithASIFragment:withInt:withNSStringArray:withIntArray:);
  methods[19].selector = @selector(onSaveInstanceStateWithASIFragment:withNSObjectArray:);
  methods[20].selector = @selector(onStartWithASIFragment:);
  methods[21].selector = @selector(onStopWithASIFragment:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "fragment_", "LASIFragment;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "heading_", "F", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "oldHeading_", "F", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "longitude_", "F", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "latitude_", "F", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "altitude_", "F", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "magneticDeclination_", "F", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "trueHeading_", "F", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "oldTrueHeading_", "F", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "stopListeners_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "locationManager_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "onCreate", "LASIFragment;[LNSObject;", "onResume", "LASIFragment;", "onPause", "onHeadingUpdate", "DDDDDD", "adjustForWrap", "DD", "smoothHeading", "onDestroy", "sendEvent", "LNSString;LJavaUtilMap;", "(Ljava/lang/String;Ljava/util/Map<Ljava/lang/String;Ljava/lang/String;>;)V", "onAttach", "onDetach", "onRequestPermissionsResult", "LASIFragment;I[LNSString;[I", "onSaveInstanceState", "onStart", "onStop" };
  static const J2ObjcClassInfo _ASCompassManager = { "CompassManager", "com.ashera.spatialkit", ptrTable, methods, fields, 7, 0x1, 22, 11, -1, -1, -1, -1, -1 };
  return &_ASCompassManager;
}

@end

void ASCompassManager_init(ASCompassManager *self) {
  NSObject_init(self);
}

ASCompassManager *new_ASCompassManager_init() {
  J2OBJC_NEW_IMPL(ASCompassManager, init)
}

ASCompassManager *create_ASCompassManager_init() {
  J2OBJC_CREATE_IMPL(ASCompassManager, init)
}

void ASCompassManager_removeListeners(ASCompassManager *self) {
  if (!self->stopListeners_) {
    ASCompassManager_stopNative(self);
  }
}

void ASCompassManager_removeAndStopListeners(ASCompassManager *self) {
  ASCompassManager_removeListeners(self);
  self->stopListeners_ = true;
}

void ASCompassManager_startNative(ASCompassManager *self) {
  self->locationManager_ = [[CLLocationManager alloc] init];
  CLLocationManager *manager = (CLLocationManager *)self->locationManager_;
  
  manager.delegate = (id<CLLocationManagerDelegate>)self;
  manager.headingFilter = 2; //Reduces noise significantly
  [manager requestWhenInUseAuthorization];
  manager.desiredAccuracy = kCLLocationAccuracyBest;
  
  [manager startUpdatingLocation];
  [manager startUpdatingHeading];
}

void ASCompassManager_stopNative(ASCompassManager *self) {
  CLLocationManager *manager = (CLLocationManager *)self->locationManager_;
  if (manager) {
    [manager stopUpdatingHeading];
    [manager stopUpdatingLocation];
  }
}

void ASCompassManager_onHeadingUpdateWithDouble_withDouble_withDouble_withDouble_withDouble_withDouble_(ASCompassManager *self, double magnetic, double trueHeadingVal, double accuracy, double lat, double lng, double alt) {
  self->oldHeading_ = self->heading_;
  if (trueHeadingVal == -1 && lat != 0 && lng != 0) {
    self->magneticDeclination_ = ASCompassHelper_calculateMagneticDeclinationWithDouble_withDouble_withDouble_(lat, lng, alt);
    trueHeadingVal = self->magneticDeclination_ + self->heading_;
  }
  trueHeadingVal = ASCompassManager_smoothHeadingWithDouble_withDouble_(self, trueHeadingVal, self->oldTrueHeading_);
  self->oldTrueHeading_ = self->trueHeading_;
  self->heading_ = (float) magnetic;
  self->trueHeading_ = (float) trueHeadingVal;
  self->latitude_ = (float) lat;
  self->longitude_ = (float) lng;
  self->altitude_ = (float) alt;
  ASCompassManager_publishResult(self);
}

double ASCompassManager_adjustForWrapWithDouble_withDouble_(ASCompassManager *self, double newHeading, double currentHeading) {
  double diff = newHeading - currentHeading;
  if (diff > 180) {
    JreMinusAssignDoubleD(&newHeading, 360);
  }
  else if (diff < -180) {
    JrePlusAssignDoubleD(&newHeading, 360);
  }
  return newHeading;
}

double ASCompassManager_smoothHeadingWithDouble_withDouble_(ASCompassManager *self, double newHeading, double currentHeading) {
  newHeading = ASCompassManager_adjustForWrapWithDouble_withDouble_(self, newHeading, currentHeading);
  double diff = JavaLangMath_absWithDouble_(newHeading - currentHeading);
  if (diff > 180) diff = 360 - diff;
  float alpha;
  if (diff > 30) {
    alpha = 0.5f;
  }
  else if (diff > 10) {
    alpha = 0.25f;
  }
  else {
    alpha = 0.08f;
  }
  double smoothed = currentHeading + alpha * (newHeading - currentHeading);
  if (smoothed < 0) JrePlusAssignDoubleD(&smoothed, 360);
  if (smoothed >= 360) JreMinusAssignDoubleD(&smoothed, 360);
  currentHeading = smoothed;
  return smoothed;
}

void ASCompassManager_onError(ASCompassManager *self) {
}

void ASCompassManager_publishResult(ASCompassManager *self) {
  id<JavaUtilMap> compassmap = new_JavaUtilHashMap_init();
  (void) [compassmap putWithId:@"heading" withId:JavaLangFloat_valueOfWithFloat_(self->heading_)];
  (void) [compassmap putWithId:@"trueHeading" withId:JavaLangFloat_valueOfWithFloat_(self->trueHeading_)];
  (void) [compassmap putWithId:@"oldHeading" withId:JavaLangFloat_valueOfWithFloat_(self->oldHeading_)];
  (void) [compassmap putWithId:@"oldTrueHeading" withId:JavaLangFloat_valueOfWithFloat_(self->oldTrueHeading_)];
  (void) [compassmap putWithId:@"latitude" withId:JavaLangFloat_valueOfWithFloat_(self->latitude_)];
  (void) [compassmap putWithId:@"longitude" withId:JavaLangFloat_valueOfWithFloat_(self->longitude_)];
  (void) [compassmap putWithId:@"altitude" withId:JavaLangFloat_valueOfWithFloat_(self->altitude_)];
  (void) [compassmap putWithId:@"magneticDeclination" withId:JavaLangFloat_valueOfWithFloat_(self->magneticDeclination_)];
  if (self->fragment_ == nil || [self->fragment_ getEventBus] == nil) {
    ASCompassManager_stopNative(self);
  }
  else {
    [((ASEventBus *) nil_chk([self->fragment_ getEventBus])) notifyObserversWithNSString:@"compass" withId:compassmap];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCompassManager)

J2OBJC_NAME_MAPPING(ASCompassManager, "com.ashera.spatialkit", "AS")
