//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\com\ashera\spatialkit\CompassViewImpl.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "CompassViewImpl.h"
#include "EventBus.h"
#include "EventBusHandler.h"
#include "IAttributable.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IWidget.h"
#include "J2ObjC_source.h"
#include "View.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Double.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/text/DecimalFormat.h"
#include "java/util/HashMap.h"
#include "java/util/Map.h"
#include "java/util/WeakHashMap.h"
#include "java/util/function/Function.h"

#include <UIKit/UIKit.h>
#include "ASUIView.h"

#import <CoreLocation/CoreLocation.h>


@class NSString;


#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


#pragma clang diagnostic ignored "-Wprotocol"

@interface ASCompassViewImpl () {
 @public
  id<ASIWidget> w_;
  id<JavaUtilMap> instances_;
  id<ASIWidget> heading2View_;
  id<ASIWidget> direction2View_;
  NSString *distanceFormat_;
  NSString *distanceUnit_;
  float targetLatitude_;
  float targetLongitude_;
}

- (instancetype)initWithASIWidget:(id<ASIWidget>)widget;

- (void)setDistanceUnitWithId:(id)objValue;

- (void)setDistanceFormatWithId:(id)objValue;

- (void)setTargetLongitudeWithId:(id)objValue;

- (void)setTargetLatitudeWithId:(id)objValue;

- (void)setDistanceTextIdWithNSString:(NSString *)strValue
                               withId:(id)objValue;

- (void)setDirection2IdWithNSString:(NSString *)strValue
                             withId:(id)objValue;

- (void)setDirectionIdWithNSString:(NSString *)strValue
                            withId:(id)objValue;

- (void)setHeadin2gIdWithNSString:(NSString *)strValue
                           withId:(id)objValue;

- (void)setHeadingIdWithNSString:(NSString *)strValue
                          withId:(id)objValue;

- (void)displayDistanceWithASIWidget:(id<ASIWidget>)distanceTextView;

- (void)headingListenerWithASIWidget:(id<ASIWidget>)headingView;

- (void)directionListenerWithASIWidget:(id<ASIWidget>)directionView;

- (void)onDestinationReachedWithId:(id)objValue;

- (void)onDestinationWithId:(id)objValue
               withNSString:(NSString *)action;

- (void)onApproachingDestinationWithId:(id)objValue;

- (float)getDistanceFromWithFloat:(float)latitude
                        withFloat:(float)longitude;

- (float)getBearingToWithFloat:(float)latitude
                     withFloat:(float)longitude;

- (void)rotateViewWithASIWidget:(id<ASIWidget>)view
                      withFloat:(float)oldTrueHeading
                      withFloat:(float)trueHeading;

@end

J2OBJC_FIELD_SETTER(ASCompassViewImpl, w_, id<ASIWidget>)
J2OBJC_FIELD_SETTER(ASCompassViewImpl, instances_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ASCompassViewImpl, heading2View_, id<ASIWidget>)
J2OBJC_FIELD_SETTER(ASCompassViewImpl, direction2View_, id<ASIWidget>)
J2OBJC_FIELD_SETTER(ASCompassViewImpl, distanceFormat_, NSString *)
J2OBJC_FIELD_SETTER(ASCompassViewImpl, distanceUnit_, NSString *)

__attribute__((unused)) static void ASCompassViewImpl_initWithASIWidget_(ASCompassViewImpl *self, id<ASIWidget> widget);

__attribute__((unused)) static ASCompassViewImpl *new_ASCompassViewImpl_initWithASIWidget_(id<ASIWidget> widget) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCompassViewImpl *create_ASCompassViewImpl_initWithASIWidget_(id<ASIWidget> widget);

__attribute__((unused)) static void ASCompassViewImpl_setDistanceUnitWithId_(ASCompassViewImpl *self, id objValue);

__attribute__((unused)) static void ASCompassViewImpl_setDistanceFormatWithId_(ASCompassViewImpl *self, id objValue);

__attribute__((unused)) static void ASCompassViewImpl_setTargetLongitudeWithId_(ASCompassViewImpl *self, id objValue);

__attribute__((unused)) static void ASCompassViewImpl_setTargetLatitudeWithId_(ASCompassViewImpl *self, id objValue);

__attribute__((unused)) static void ASCompassViewImpl_setDistanceTextIdWithNSString_withId_(ASCompassViewImpl *self, NSString *strValue, id objValue);

__attribute__((unused)) static void ASCompassViewImpl_setDirection2IdWithNSString_withId_(ASCompassViewImpl *self, NSString *strValue, id objValue);

__attribute__((unused)) static void ASCompassViewImpl_setDirectionIdWithNSString_withId_(ASCompassViewImpl *self, NSString *strValue, id objValue);

__attribute__((unused)) static void ASCompassViewImpl_setHeadin2gIdWithNSString_withId_(ASCompassViewImpl *self, NSString *strValue, id objValue);

__attribute__((unused)) static void ASCompassViewImpl_setHeadingIdWithNSString_withId_(ASCompassViewImpl *self, NSString *strValue, id objValue);

__attribute__((unused)) static void ASCompassViewImpl_displayDistanceWithASIWidget_(ASCompassViewImpl *self, id<ASIWidget> distanceTextView);

__attribute__((unused)) static void ASCompassViewImpl_headingListenerWithASIWidget_(ASCompassViewImpl *self, id<ASIWidget> headingView);

__attribute__((unused)) static void ASCompassViewImpl_directionListenerWithASIWidget_(ASCompassViewImpl *self, id<ASIWidget> directionView);

__attribute__((unused)) static void ASCompassViewImpl_onDestinationReachedWithId_(ASCompassViewImpl *self, id objValue);

__attribute__((unused)) static void ASCompassViewImpl_onDestinationWithId_withNSString_(ASCompassViewImpl *self, id objValue, NSString *action);

__attribute__((unused)) static void ASCompassViewImpl_onApproachingDestinationWithId_(ASCompassViewImpl *self, id objValue);

__attribute__((unused)) static float ASCompassViewImpl_getDistanceFromWithFloat_withFloat_(ASCompassViewImpl *self, float latitude, float longitude);

__attribute__((unused)) static float ASCompassViewImpl_getBearingToWithFloat_withFloat_(ASCompassViewImpl *self, float latitude, float longitude);

__attribute__((unused)) static void ASCompassViewImpl_rotateViewWithASIWidget_withFloat_withFloat_(ASCompassViewImpl *self, id<ASIWidget> view, float oldTrueHeading, float trueHeading);

@interface ASCompassViewImpl_1 : ASEventBusHandler {
 @public
  ASCompassViewImpl *this$0_;
  id<ASIWidget> val$distanceTextView_;
}

- (instancetype)initWithASCompassViewImpl:(ASCompassViewImpl *)outer$
                            withASIWidget:(id<ASIWidget>)capture$0
                             withNSString:(NSString *)type;

- (void)doPerformWithId:(id)payload;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCompassViewImpl_1)

__attribute__((unused)) static void ASCompassViewImpl_1_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl_1 *self, ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type);

__attribute__((unused)) static ASCompassViewImpl_1 *new_ASCompassViewImpl_1_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCompassViewImpl_1 *create_ASCompassViewImpl_1_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type);


@interface ASCompassViewImpl_2 : ASEventBusHandler {
 @public
  ASCompassViewImpl *this$0_;
  id<ASIWidget> val$headingView_;
}

- (instancetype)initWithASCompassViewImpl:(ASCompassViewImpl *)outer$
                            withASIWidget:(id<ASIWidget>)capture$0
                             withNSString:(NSString *)type;

- (void)doPerformWithId:(id)payload;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCompassViewImpl_2)

__attribute__((unused)) static void ASCompassViewImpl_2_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl_2 *self, ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type);

__attribute__((unused)) static ASCompassViewImpl_2 *new_ASCompassViewImpl_2_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCompassViewImpl_2 *create_ASCompassViewImpl_2_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type);


@interface ASCompassViewImpl_3 : ASEventBusHandler {
 @public
  ASCompassViewImpl *this$0_;
  id<ASIWidget> val$directionView_;
}

- (instancetype)initWithASCompassViewImpl:(ASCompassViewImpl *)outer$
                            withASIWidget:(id<ASIWidget>)capture$0
                             withNSString:(NSString *)type;

- (void)doPerformWithId:(id)payload;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCompassViewImpl_3)

__attribute__((unused)) static void ASCompassViewImpl_3_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl_3 *self, ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type);

__attribute__((unused)) static ASCompassViewImpl_3 *new_ASCompassViewImpl_3_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCompassViewImpl_3 *create_ASCompassViewImpl_3_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type);


@interface ASCompassViewImpl_4 : ASEventBusHandler {
 @public
  ASCompassViewImpl *this$0_;
  int32_t val$tolerance_;
  NSString *val$action_;
  bool flag_;
}

- (instancetype)initWithASCompassViewImpl:(ASCompassViewImpl *)outer$
                                  withInt:(int32_t)capture$0
                             withNSString:(NSString *)capture$1
                             withNSString:(NSString *)type;

- (void)doPerformWithId:(id)payload;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCompassViewImpl_4)

__attribute__((unused)) static void ASCompassViewImpl_4_initWithASCompassViewImpl_withInt_withNSString_withNSString_(ASCompassViewImpl_4 *self, ASCompassViewImpl *outer$, int32_t capture$0, NSString *capture$1, NSString *type);

__attribute__((unused)) static ASCompassViewImpl_4 *new_ASCompassViewImpl_4_initWithASCompassViewImpl_withInt_withNSString_withNSString_(ASCompassViewImpl *outer$, int32_t capture$0, NSString *capture$1, NSString *type) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCompassViewImpl_4 *create_ASCompassViewImpl_4_initWithASCompassViewImpl_withInt_withNSString_withNSString_(ASCompassViewImpl *outer$, int32_t capture$0, NSString *capture$1, NSString *type);


@interface ASCompassViewImpl_$Lambda$1 : NSObject < JavaUtilFunctionFunction >

- (id)applyWithId:(id<ASIWidget>)w;

@end

J2OBJC_STATIC_INIT(ASCompassViewImpl_$Lambda$1)

inline ASCompassViewImpl_$Lambda$1 *ASCompassViewImpl_$Lambda$1_get_instance(void);
static ASCompassViewImpl_$Lambda$1 *ASCompassViewImpl_$Lambda$1_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCompassViewImpl_$Lambda$1, instance, ASCompassViewImpl_$Lambda$1 *)

__attribute__((unused)) static void ASCompassViewImpl_$Lambda$1_init(ASCompassViewImpl_$Lambda$1 *self);

__attribute__((unused)) static ASCompassViewImpl_$Lambda$1 *new_ASCompassViewImpl_$Lambda$1_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCompassViewImpl_$Lambda$1 *create_ASCompassViewImpl_$Lambda$1_init(void);


NSString *ASCompassViewImpl_LOCAL_NAME = @"CompassView";

@implementation ASCompassViewImpl

- (instancetype)initWithASIWidget:(id<ASIWidget>)widget {
  ASCompassViewImpl_initWithASIWidget_(self, widget);
  return self;
}

- (NSString *)getLocalName {
  return ASCompassViewImpl_LOCAL_NAME;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCompassViewImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<ASIAttributable>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  return [((id<JavaUtilMap>) nil_chk(instances_)) computeIfAbsentWithId:widget withJavaUtilFunctionFunction:JreLoadStatic(ASCompassViewImpl_$Lambda$1, instance)];
}

- (void)loadAttributesWithNSString:(NSString *)localName {
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"headingId"])) withTypeWithNSString:@"id"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"heading2Id"])) withTypeWithNSString:@"id"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"directionId"])) withTypeWithNSString:@"id"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"direction2Id"])) withTypeWithNSString:@"id"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"distanceTextId"])) withTypeWithNSString:@"id"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"targetLatitude"])) withTypeWithNSString:@"float"])) withOrderWithInt:-1]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"targetLongitude"])) withTypeWithNSString:@"float"])) withOrderWithInt:-1]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"distanceFormat"])) withTypeWithNSString:@"resourcestring"])) withOrderWithInt:-1]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"distanceUnit"])) withTypeWithNSString:@"resourcestring"])) withOrderWithInt:-1]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"onDestinationReached"])) withTypeWithNSString:@"int"])) withOrderWithInt:-1]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"onApproachingDestination"])) withTypeWithNSString:@"int"])) withOrderWithInt:-1]);
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w_)) asWidget], [ADView class]);
  id nativeWidget = [((id<ASIWidget>) nil_chk(w_)) asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"headingId", @"heading2Id", @"directionId", @"direction2Id", @"distanceTextId", @"targetLatitude", @"targetLongitude", @"distanceFormat", @"distanceUnit", @"onDestinationReached", @"onApproachingDestination" }, 11)) {
    case 0:
    {
      ASCompassViewImpl_setHeadingIdWithNSString_withId_(self, strValue, objValue);
    }
    break;
    case 1:
    {
      ASCompassViewImpl_setHeadin2gIdWithNSString_withId_(self, strValue, objValue);
    }
    break;
    case 2:
    {
      ASCompassViewImpl_setDirectionIdWithNSString_withId_(self, strValue, objValue);
    }
    break;
    case 3:
    {
      ASCompassViewImpl_setDirection2IdWithNSString_withId_(self, strValue, objValue);
    }
    break;
    case 4:
    {
      ASCompassViewImpl_setDistanceTextIdWithNSString_withId_(self, strValue, objValue);
    }
    break;
    case 5:
    {
      ASCompassViewImpl_setTargetLatitudeWithId_(self, objValue);
    }
    break;
    case 6:
    {
      ASCompassViewImpl_setTargetLongitudeWithId_(self, objValue);
    }
    break;
    case 7:
    {
      ASCompassViewImpl_setDistanceFormatWithId_(self, objValue);
    }
    break;
    case 8:
    {
      ASCompassViewImpl_setDistanceUnitWithId_(self, objValue);
    }
    break;
    case 9:
    {
      ASCompassViewImpl_onDestinationReachedWithId_(self, objValue);
    }
    break;
    case 10:
    {
      ASCompassViewImpl_onApproachingDestinationWithId_(self, objValue);
    }
    break;
    default:
    break;
  }
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w_)) asWidget], [ADView class]);
  id nativeWidget = [((id<ASIWidget>) nil_chk(w_)) asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){  }, 0)) {
  }
  return nil;
}

- (void)setDistanceUnitWithId:(id)objValue {
  ASCompassViewImpl_setDistanceUnitWithId_(self, objValue);
}

- (void)setDistanceFormatWithId:(id)objValue {
  ASCompassViewImpl_setDistanceFormatWithId_(self, objValue);
}

- (void)setTargetLongitudeWithId:(id)objValue {
  ASCompassViewImpl_setTargetLongitudeWithId_(self, objValue);
}

- (void)setTargetLatitudeWithId:(id)objValue {
  ASCompassViewImpl_setTargetLatitudeWithId_(self, objValue);
}

- (void)setDistanceTextIdWithNSString:(NSString *)strValue
                               withId:(id)objValue {
  ASCompassViewImpl_setDistanceTextIdWithNSString_withId_(self, strValue, objValue);
}

- (void)setDirection2IdWithNSString:(NSString *)strValue
                             withId:(id)objValue {
  ASCompassViewImpl_setDirection2IdWithNSString_withId_(self, strValue, objValue);
}

- (void)setDirectionIdWithNSString:(NSString *)strValue
                            withId:(id)objValue {
  ASCompassViewImpl_setDirectionIdWithNSString_withId_(self, strValue, objValue);
}

- (void)setHeadin2gIdWithNSString:(NSString *)strValue
                           withId:(id)objValue {
  ASCompassViewImpl_setHeadin2gIdWithNSString_withId_(self, strValue, objValue);
}

- (void)setHeadingIdWithNSString:(NSString *)strValue
                          withId:(id)objValue {
  ASCompassViewImpl_setHeadingIdWithNSString_withId_(self, strValue, objValue);
}

- (void)displayDistanceWithASIWidget:(id<ASIWidget>)distanceTextView {
  ASCompassViewImpl_displayDistanceWithASIWidget_(self, distanceTextView);
}

- (void)headingListenerWithASIWidget:(id<ASIWidget>)headingView {
  ASCompassViewImpl_headingListenerWithASIWidget_(self, headingView);
}

- (void)directionListenerWithASIWidget:(id<ASIWidget>)directionView {
  ASCompassViewImpl_directionListenerWithASIWidget_(self, directionView);
}

- (void)onDestinationReachedWithId:(id)objValue {
  ASCompassViewImpl_onDestinationReachedWithId_(self, objValue);
}

- (void)onDestinationWithId:(id)objValue
               withNSString:(NSString *)action {
  ASCompassViewImpl_onDestinationWithId_withNSString_(self, objValue, action);
}

- (void)onApproachingDestinationWithId:(id)objValue {
  ASCompassViewImpl_onApproachingDestinationWithId_(self, objValue);
}

- (float)getDistanceFromWithFloat:(float)latitude
                        withFloat:(float)longitude {
  return ASCompassViewImpl_getDistanceFromWithFloat_withFloat_(self, latitude, longitude);
}

- (float)getBearingToWithFloat:(float)latitude
                     withFloat:(float)longitude {
  return ASCompassViewImpl_getBearingToWithFloat_withFloat_(self, latitude, longitude);
}

- (void)rotateViewWithASIWidget:(id<ASIWidget>)view
                      withFloat:(float)oldTrueHeading
                      withFloat:(float)trueHeading {
  ASCompassViewImpl_rotateViewWithASIWidget_withFloat_withFloat_(self, view, oldTrueHeading, trueHeading);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASIAttributable;", 0x1, 1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 10, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 11, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 12, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 13, 14, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 15, 14, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 16, 14, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 17, 14, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 18, 14, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 19, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 20, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 21, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 22, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 23, 24, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 25, 9, -1, -1, -1, -1 },
    { NULL, "F", 0x102, 26, 27, -1, -1, -1, -1 },
    { NULL, "F", 0x102, 28, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 29, 30, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASIWidget:);
  methods[1].selector = @selector(getLocalName);
  methods[2].selector = @selector(init);
  methods[3].selector = @selector(newInstanceWithASIWidget:);
  methods[4].selector = @selector(loadAttributesWithNSString:);
  methods[5].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[6].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[7].selector = @selector(setDistanceUnitWithId:);
  methods[8].selector = @selector(setDistanceFormatWithId:);
  methods[9].selector = @selector(setTargetLongitudeWithId:);
  methods[10].selector = @selector(setTargetLatitudeWithId:);
  methods[11].selector = @selector(setDistanceTextIdWithNSString:withId:);
  methods[12].selector = @selector(setDirection2IdWithNSString:withId:);
  methods[13].selector = @selector(setDirectionIdWithNSString:withId:);
  methods[14].selector = @selector(setHeadin2gIdWithNSString:withId:);
  methods[15].selector = @selector(setHeadingIdWithNSString:withId:);
  methods[16].selector = @selector(displayDistanceWithASIWidget:);
  methods[17].selector = @selector(headingListenerWithASIWidget:);
  methods[18].selector = @selector(directionListenerWithASIWidget:);
  methods[19].selector = @selector(onDestinationReachedWithId:);
  methods[20].selector = @selector(onDestinationWithId:withNSString:);
  methods[21].selector = @selector(onApproachingDestinationWithId:);
  methods[22].selector = @selector(getDistanceFromWithFloat:withFloat:);
  methods[23].selector = @selector(getBearingToWithFloat:withFloat:);
  methods[24].selector = @selector(rotateViewWithASIWidget:withFloat:withFloat:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 31, -1, -1 },
    { "w_", "LASIWidget;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "instances_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 32, -1 },
    { "heading2View_", "LASIWidget;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "direction2View_", "LASIWidget;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "distanceFormat_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "distanceUnit_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "targetLatitude_", "F", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "targetLongitude_", "F", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASIWidget;", "newInstance", "loadAttributes", "LNSString;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "setDistanceUnit", "LNSObject;", "setDistanceFormat", "setTargetLongitude", "setTargetLatitude", "setDistanceTextId", "LNSString;LNSObject;", "setDirection2Id", "setDirectionId", "setHeadin2gId", "setHeadingId", "displayDistance", "headingListener", "directionListener", "onDestinationReached", "onDestination", "LNSObject;LNSString;", "onApproachingDestination", "getDistanceFrom", "FF", "getBearingTo", "rotateView", "LASIWidget;FF", &ASCompassViewImpl_LOCAL_NAME, "Ljava/util/Map<Lcom/ashera/widget/IWidget;Lcom/ashera/widget/IAttributable;>;" };
  static const J2ObjcClassInfo _ASCompassViewImpl = { "CompassViewImpl", "com.ashera.spatialkit", ptrTable, methods, fields, 7, 0x1, 25, 9, -1, -1, -1, -1, -1 };
  return &_ASCompassViewImpl;
}

@end

void ASCompassViewImpl_initWithASIWidget_(ASCompassViewImpl *self, id<ASIWidget> widget) {
  NSObject_init(self);
  self->instances_ = new_JavaUtilWeakHashMap_init();
  self->distanceFormat_ = @"%s";
  self->distanceUnit_ = @"km";
  self->w_ = widget;
}

ASCompassViewImpl *new_ASCompassViewImpl_initWithASIWidget_(id<ASIWidget> widget) {
  J2OBJC_NEW_IMPL(ASCompassViewImpl, initWithASIWidget_, widget)
}

ASCompassViewImpl *create_ASCompassViewImpl_initWithASIWidget_(id<ASIWidget> widget) {
  J2OBJC_CREATE_IMPL(ASCompassViewImpl, initWithASIWidget_, widget)
}

void ASCompassViewImpl_init(ASCompassViewImpl *self) {
  NSObject_init(self);
  self->instances_ = new_JavaUtilWeakHashMap_init();
  self->distanceFormat_ = @"%s";
  self->distanceUnit_ = @"km";
}

ASCompassViewImpl *new_ASCompassViewImpl_init() {
  J2OBJC_NEW_IMPL(ASCompassViewImpl, init)
}

ASCompassViewImpl *create_ASCompassViewImpl_init() {
  J2OBJC_CREATE_IMPL(ASCompassViewImpl, init)
}

void ASCompassViewImpl_setDistanceUnitWithId_(ASCompassViewImpl *self, id objValue) {
  self->distanceUnit_ = (NSString *) cast_chk(objValue, [NSString class]);
}

void ASCompassViewImpl_setDistanceFormatWithId_(ASCompassViewImpl *self, id objValue) {
  self->distanceFormat_ = (NSString *) cast_chk(objValue, [NSString class]);
}

void ASCompassViewImpl_setTargetLongitudeWithId_(ASCompassViewImpl *self, id objValue) {
  self->targetLongitude_ = [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class]))) floatValue];
}

void ASCompassViewImpl_setTargetLatitudeWithId_(ASCompassViewImpl *self, id objValue) {
  self->targetLatitude_ = [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class]))) floatValue];
}

void ASCompassViewImpl_setDistanceTextIdWithNSString_withId_(ASCompassViewImpl *self, NSString *strValue, id objValue) {
  id<ASIWidget> distanceTextView = [((id<ASIWidget>) nil_chk(self->w_)) findWidgetByIdWithNSString:strValue];
  ASCompassViewImpl_displayDistanceWithASIWidget_(self, distanceTextView);
}

void ASCompassViewImpl_setDirection2IdWithNSString_withId_(ASCompassViewImpl *self, NSString *strValue, id objValue) {
  self->direction2View_ = [((id<ASIWidget>) nil_chk(self->w_)) findWidgetByIdWithNSString:strValue];
}

void ASCompassViewImpl_setDirectionIdWithNSString_withId_(ASCompassViewImpl *self, NSString *strValue, id objValue) {
  id<ASIWidget> directionView = [((id<ASIWidget>) nil_chk(self->w_)) findWidgetByIdWithNSString:strValue];
  ASCompassViewImpl_directionListenerWithASIWidget_(self, directionView);
}

void ASCompassViewImpl_setHeadin2gIdWithNSString_withId_(ASCompassViewImpl *self, NSString *strValue, id objValue) {
  self->heading2View_ = [((id<ASIWidget>) nil_chk(self->w_)) findWidgetByIdWithNSString:strValue];
}

void ASCompassViewImpl_setHeadingIdWithNSString_withId_(ASCompassViewImpl *self, NSString *strValue, id objValue) {
  id<ASIWidget> headingView = [((id<ASIWidget>) nil_chk(self->w_)) findWidgetByIdWithNSString:strValue];
  ASCompassViewImpl_headingListenerWithASIWidget_(self, headingView);
}

void ASCompassViewImpl_displayDistanceWithASIWidget_(ASCompassViewImpl *self, id<ASIWidget> distanceTextView) {
  [((ASEventBus *) nil_chk([((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(self->w_)) getFragment])) getEventBus])) onWithNSString:@"compass" withASEventBusHandlerArray:[IOSObjectArray newArrayWithObjects:(id[]){ create_ASCompassViewImpl_1_initWithASCompassViewImpl_withASIWidget_withNSString_(self, distanceTextView, @"compass") } count:1 type:ASEventBusHandler_class_()]];
}

void ASCompassViewImpl_headingListenerWithASIWidget_(ASCompassViewImpl *self, id<ASIWidget> headingView) {
  if (headingView != nil) {
    [((ASEventBus *) nil_chk([((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(self->w_)) getFragment])) getEventBus])) onWithNSString:@"compass" withASEventBusHandlerArray:[IOSObjectArray newArrayWithObjects:(id[]){ create_ASCompassViewImpl_2_initWithASCompassViewImpl_withASIWidget_withNSString_(self, headingView, @"compass") } count:1 type:ASEventBusHandler_class_()]];
  }
}

void ASCompassViewImpl_directionListenerWithASIWidget_(ASCompassViewImpl *self, id<ASIWidget> directionView) {
  if (directionView != nil) {
    [((ASEventBus *) nil_chk([((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(self->w_)) getFragment])) getEventBus])) onWithNSString:@"compass" withASEventBusHandlerArray:[IOSObjectArray newArrayWithObjects:(id[]){ create_ASCompassViewImpl_3_initWithASCompassViewImpl_withASIWidget_withNSString_(self, directionView, @"compass") } count:1 type:ASEventBusHandler_class_()]];
  }
}

void ASCompassViewImpl_onDestinationReachedWithId_(ASCompassViewImpl *self, id objValue) {
  ASCompassViewImpl_onDestinationWithId_withNSString_(self, objValue, @"onDestinationReached");
}

void ASCompassViewImpl_onDestinationWithId_withNSString_(ASCompassViewImpl *self, id objValue, NSString *action) {
  int32_t tolerance = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
  [((ASEventBus *) nil_chk([((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(self->w_)) getFragment])) getEventBus])) onWithNSString:@"compass" withASEventBusHandlerArray:[IOSObjectArray newArrayWithObjects:(id[]){ create_ASCompassViewImpl_4_initWithASCompassViewImpl_withInt_withNSString_withNSString_(self, tolerance, action, @"compass") } count:1 type:ASEventBusHandler_class_()]];
}

void ASCompassViewImpl_onApproachingDestinationWithId_(ASCompassViewImpl *self, id objValue) {
  ASCompassViewImpl_onDestinationWithId_withNSString_(self, objValue, @"onApproachingDestination");
}

float ASCompassViewImpl_getDistanceFromWithFloat_withFloat_(ASCompassViewImpl *self, float latitude, float longitude) {
  CLLocation *currentLocation = [[CLLocation alloc] initWithLatitude:latitude
  longitude:longitude];
  
  CLLocation *targetLocation = [[CLLocation alloc] initWithLatitude:self->targetLatitude_
  longitude:self->targetLongitude_];
  
  CLLocationDistance distance = [currentLocation distanceFromLocation:targetLocation];
  
  return (float)distance;
}

float ASCompassViewImpl_getBearingToWithFloat_withFloat_(ASCompassViewImpl *self, float latitude, float longitude) {
  double lat1 = latitude * M_PI / 180.0;
  double lon1 = longitude * M_PI / 180.0;
  double lat2 = self->targetLatitude_ * M_PI / 180.0;
  double lon2 = self->targetLongitude_ * M_PI / 180.0;
  
  double dLon = lon2 - lon1;
  
  double y = sin(dLon) * cos(lat2);
  double x = cos(lat1) * sin(lat2) -
  sin(lat1) * cos(lat2) * cos(dLon);
  
  double bearing = atan2(y, x);
  
  // Convert radians -> degrees
  bearing = bearing * 180.0 / M_PI;
  
  // Normalize to 0–360
  if (bearing < 0) {
    bearing += 360.0;
  }
  
  return (float)bearing;
}

void ASCompassViewImpl_rotateViewWithASIWidget_withFloat_withFloat_(ASCompassViewImpl *self, id<ASIWidget> view, float oldTrueHeading, float trueHeading) {
  UIView *uiView = (UIView *)[view asNativeWidget];
  
  // Convert degrees -> radians
  CGFloat fromAngle = -oldTrueHeading * M_PI / 180.0;
  CGFloat toAngle   = -trueHeading * M_PI / 180.0;
  
  // Create rotation animation
  CABasicAnimation *rotation = [CABasicAnimation animationWithKeyPath:@"transform.rotation.z"];
  rotation.fromValue = @(fromAngle);
  rotation.toValue = @(toAngle);
  rotation.duration = 0.2;
  rotation.fillMode = kCAFillModeForwards;
  rotation.removedOnCompletion = NO;
  
  // Apply animation
  [uiView.layer addAnimation:rotation forKey:@"rotateAnimation"];
  
  // Important: set final state (otherwise it snaps back later)
  uiView.layer.transform = CATransform3DMakeRotation(toAngle, 0, 0, 1);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCompassViewImpl)

J2OBJC_NAME_MAPPING(ASCompassViewImpl, "com.ashera.spatialkit", "AS")

@implementation ASCompassViewImpl_1

- (instancetype)initWithASCompassViewImpl:(ASCompassViewImpl *)outer$
                            withASIWidget:(id<ASIWidget>)capture$0
                             withNSString:(NSString *)type {
  ASCompassViewImpl_1_initWithASCompassViewImpl_withASIWidget_withNSString_(self, outer$, capture$0, type);
  return self;
}

- (void)doPerformWithId:(id)payload {
  id<JavaUtilMap> compassmap = (id<JavaUtilMap>) cast_check(payload, JavaUtilMap_class_());
  float latitude = [((JavaLangFloat *) nil_chk([((id<JavaUtilMap>) nil_chk(compassmap)) getWithId:@"latitude"])) floatValue];
  float longitude = [((JavaLangFloat *) nil_chk([compassmap getWithId:@"longitude"])) floatValue];
  if (latitude != 0 && longitude != 0 && this$0_->targetLatitude_ != 0 && this$0_->targetLongitude_ != 0) {
    float distance = ASCompassViewImpl_getDistanceFromWithFloat_withFloat_(this$0_, latitude, longitude);
    NSString *formattedDistance = nil;
    switch (JreIndexOfStr(this$0_->distanceUnit_, (id[]){ @"km", @"mile" }, 2)) {
      case 0:
      if (distance < 1000) {
        if (distance == 0) {
          formattedDistance = @"";
        }
        else {
          formattedDistance = NSString_java_formatWithNSString_withNSObjectArray_(this$0_->distanceFormat_, [IOSObjectArray newArrayWithObjects:(id[]){ [create_JavaTextDecimalFormat_initWithNSString_(@"## M") formatWithDouble:distance] } count:1 type:NSObject_class_()]);
        }
      }
      else if (distance < 1000 * 100) {
        formattedDistance = NSString_java_formatWithNSString_withNSObjectArray_(this$0_->distanceFormat_, [IOSObjectArray newArrayWithObjects:(id[]){ [create_JavaTextDecimalFormat_initWithNSString_(@"##.## KM") formatWithDouble:distance / 1000] } count:1 type:NSObject_class_()]);
      }
      else {
        formattedDistance = NSString_java_formatWithNSString_withNSObjectArray_(this$0_->distanceFormat_, [IOSObjectArray newArrayWithObjects:(id[]){ [create_JavaTextDecimalFormat_initWithNSString_(@"## KM") formatWithDouble:distance / 1000] } count:1 type:NSObject_class_()]);
      }
      break;
      case 1:
      formattedDistance = NSString_java_formatWithNSString_withNSObjectArray_(this$0_->distanceFormat_, [IOSObjectArray newArrayWithObjects:(id[]){ [create_JavaTextDecimalFormat_initWithNSString_(@"## MILE") formatWithDouble:distance / 1609.344] } count:1 type:NSObject_class_()]);
      break;
      default:
      break;
    }
    [((id<ASIWidget>) nil_chk(val$distanceTextView_)) setAttributeWithNSString:@"text" withId:formattedDistance withBoolean:false];
    [val$distanceTextView_ requestLayout];
    [((id<ASIFragment>) nil_chk([val$distanceTextView_ getFragment])) remeasure];
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASCompassViewImpl:withASIWidget:withNSString:);
  methods[1].selector = @selector(doPerformWithId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASCompassViewImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$distanceTextView_", "LASIWidget;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASCompassViewImpl;LASIWidget;LNSString;", "doPerform", "LNSObject;", "LASCompassViewImpl;", "displayDistanceWithASIWidget:" };
  static const J2ObjcClassInfo _ASCompassViewImpl_1 = { "", "com.ashera.spatialkit", ptrTable, methods, fields, 7, 0x8000, 2, 2, 3, -1, 4, -1, -1 };
  return &_ASCompassViewImpl_1;
}

@end

void ASCompassViewImpl_1_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl_1 *self, ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type) {
  self->this$0_ = outer$;
  self->val$distanceTextView_ = capture$0;
  ASEventBusHandler_initWithNSString_(self, type);
}

ASCompassViewImpl_1 *new_ASCompassViewImpl_1_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type) {
  J2OBJC_NEW_IMPL(ASCompassViewImpl_1, initWithASCompassViewImpl_withASIWidget_withNSString_, outer$, capture$0, type)
}

ASCompassViewImpl_1 *create_ASCompassViewImpl_1_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type) {
  J2OBJC_CREATE_IMPL(ASCompassViewImpl_1, initWithASCompassViewImpl_withASIWidget_withNSString_, outer$, capture$0, type)
}

@implementation ASCompassViewImpl_2

- (instancetype)initWithASCompassViewImpl:(ASCompassViewImpl *)outer$
                            withASIWidget:(id<ASIWidget>)capture$0
                             withNSString:(NSString *)type {
  ASCompassViewImpl_2_initWithASCompassViewImpl_withASIWidget_withNSString_(self, outer$, capture$0, type);
  return self;
}

- (void)doPerformWithId:(id)payload {
  id<JavaUtilMap> compassmap = (id<JavaUtilMap>) cast_check(payload, JavaUtilMap_class_());
  float oldTrueHeading = [((JavaLangFloat *) nil_chk([((id<JavaUtilMap>) nil_chk(compassmap)) getWithId:@"oldTrueHeading"])) floatValue];
  float trueHeading = [((JavaLangFloat *) nil_chk([compassmap getWithId:@"trueHeading"])) floatValue];
  ASCompassViewImpl_rotateViewWithASIWidget_withFloat_withFloat_(this$0_, val$headingView_, oldTrueHeading, trueHeading);
  if (this$0_->heading2View_ != nil) {
    ASCompassViewImpl_rotateViewWithASIWidget_withFloat_withFloat_(this$0_, this$0_->heading2View_, oldTrueHeading, trueHeading);
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASCompassViewImpl:withASIWidget:withNSString:);
  methods[1].selector = @selector(doPerformWithId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASCompassViewImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$headingView_", "LASIWidget;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASCompassViewImpl;LASIWidget;LNSString;", "doPerform", "LNSObject;", "LASCompassViewImpl;", "headingListenerWithASIWidget:" };
  static const J2ObjcClassInfo _ASCompassViewImpl_2 = { "", "com.ashera.spatialkit", ptrTable, methods, fields, 7, 0x8000, 2, 2, 3, -1, 4, -1, -1 };
  return &_ASCompassViewImpl_2;
}

@end

void ASCompassViewImpl_2_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl_2 *self, ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type) {
  self->this$0_ = outer$;
  self->val$headingView_ = capture$0;
  ASEventBusHandler_initWithNSString_(self, type);
}

ASCompassViewImpl_2 *new_ASCompassViewImpl_2_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type) {
  J2OBJC_NEW_IMPL(ASCompassViewImpl_2, initWithASCompassViewImpl_withASIWidget_withNSString_, outer$, capture$0, type)
}

ASCompassViewImpl_2 *create_ASCompassViewImpl_2_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type) {
  J2OBJC_CREATE_IMPL(ASCompassViewImpl_2, initWithASCompassViewImpl_withASIWidget_withNSString_, outer$, capture$0, type)
}

@implementation ASCompassViewImpl_3

- (instancetype)initWithASCompassViewImpl:(ASCompassViewImpl *)outer$
                            withASIWidget:(id<ASIWidget>)capture$0
                             withNSString:(NSString *)type {
  ASCompassViewImpl_3_initWithASCompassViewImpl_withASIWidget_withNSString_(self, outer$, capture$0, type);
  return self;
}

- (void)doPerformWithId:(id)payload {
  id<JavaUtilMap> compassmap = (id<JavaUtilMap>) cast_check(payload, JavaUtilMap_class_());
  float oldTrueHeading = [((JavaLangFloat *) nil_chk([((id<JavaUtilMap>) nil_chk(compassmap)) getWithId:@"oldTrueHeading"])) floatValue];
  float trueHeading = [((JavaLangFloat *) nil_chk([compassmap getWithId:@"trueHeading"])) floatValue];
  float latitude = [((JavaLangFloat *) nil_chk([compassmap getWithId:@"latitude"])) floatValue];
  float longitude = [((JavaLangFloat *) nil_chk([compassmap getWithId:@"longitude"])) floatValue];
  if (latitude != 0 && longitude != 0 && this$0_->targetLatitude_ != 0 && this$0_->targetLongitude_ != 0 && trueHeading != 0) {
    float bearing = ASCompassViewImpl_getBearingToWithFloat_withFloat_(this$0_, latitude, longitude);
    float degree = trueHeading - bearing;
    float olddegree = oldTrueHeading - bearing;
    ASCompassViewImpl_rotateViewWithASIWidget_withFloat_withFloat_(this$0_, val$directionView_, degree, olddegree);
    if (this$0_->direction2View_ != nil) {
      ASCompassViewImpl_rotateViewWithASIWidget_withFloat_withFloat_(this$0_, this$0_->direction2View_, degree, olddegree);
    }
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASCompassViewImpl:withASIWidget:withNSString:);
  methods[1].selector = @selector(doPerformWithId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASCompassViewImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$directionView_", "LASIWidget;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASCompassViewImpl;LASIWidget;LNSString;", "doPerform", "LNSObject;", "LASCompassViewImpl;", "directionListenerWithASIWidget:" };
  static const J2ObjcClassInfo _ASCompassViewImpl_3 = { "", "com.ashera.spatialkit", ptrTable, methods, fields, 7, 0x8000, 2, 2, 3, -1, 4, -1, -1 };
  return &_ASCompassViewImpl_3;
}

@end

void ASCompassViewImpl_3_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl_3 *self, ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type) {
  self->this$0_ = outer$;
  self->val$directionView_ = capture$0;
  ASEventBusHandler_initWithNSString_(self, type);
}

ASCompassViewImpl_3 *new_ASCompassViewImpl_3_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type) {
  J2OBJC_NEW_IMPL(ASCompassViewImpl_3, initWithASCompassViewImpl_withASIWidget_withNSString_, outer$, capture$0, type)
}

ASCompassViewImpl_3 *create_ASCompassViewImpl_3_initWithASCompassViewImpl_withASIWidget_withNSString_(ASCompassViewImpl *outer$, id<ASIWidget> capture$0, NSString *type) {
  J2OBJC_CREATE_IMPL(ASCompassViewImpl_3, initWithASCompassViewImpl_withASIWidget_withNSString_, outer$, capture$0, type)
}

@implementation ASCompassViewImpl_4

- (instancetype)initWithASCompassViewImpl:(ASCompassViewImpl *)outer$
                                  withInt:(int32_t)capture$0
                             withNSString:(NSString *)capture$1
                             withNSString:(NSString *)type {
  ASCompassViewImpl_4_initWithASCompassViewImpl_withInt_withNSString_withNSString_(self, outer$, capture$0, capture$1, type);
  return self;
}

- (void)doPerformWithId:(id)payload {
  id<JavaUtilMap> compassmap = (id<JavaUtilMap>) cast_check(payload, JavaUtilMap_class_());
  float latitude = [((JavaLangFloat *) nil_chk([((id<JavaUtilMap>) nil_chk(compassmap)) getWithId:@"latitude"])) floatValue];
  float longitude = [((JavaLangFloat *) nil_chk([compassmap getWithId:@"longitude"])) floatValue];
  if (latitude != 0 && longitude != 0 && this$0_->targetLatitude_ != 0 && this$0_->targetLongitude_ != 0) {
    float distance = ASCompassViewImpl_getDistanceFromWithFloat_withFloat_(this$0_, latitude, longitude);
    if (!flag_ && distance < val$tolerance_) {
      id<JavaUtilMap> obj = new_JavaUtilHashMap_init();
      (void) [obj putWithId:@"distance" withId:[new_JavaTextDecimalFormat_initWithNSString_(@"##.##") formatWithDouble:distance]];
      [((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(this$0_->w_)) getFragment])) sendEventWithNSString:val$action_ withJavaUtilMap:obj];
      flag_ = true;
    }
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASCompassViewImpl:withInt:withNSString:withNSString:);
  methods[1].selector = @selector(doPerformWithId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASCompassViewImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$tolerance_", "I", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$action_", "LNSString;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "flag_", "Z", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASCompassViewImpl;ILNSString;LNSString;", "doPerform", "LNSObject;", "LASCompassViewImpl;", "onDestinationWithId:withNSString:" };
  static const J2ObjcClassInfo _ASCompassViewImpl_4 = { "", "com.ashera.spatialkit", ptrTable, methods, fields, 7, 0x8000, 2, 4, 3, -1, 4, -1, -1 };
  return &_ASCompassViewImpl_4;
}

@end

void ASCompassViewImpl_4_initWithASCompassViewImpl_withInt_withNSString_withNSString_(ASCompassViewImpl_4 *self, ASCompassViewImpl *outer$, int32_t capture$0, NSString *capture$1, NSString *type) {
  self->this$0_ = outer$;
  self->val$tolerance_ = capture$0;
  self->val$action_ = capture$1;
  ASEventBusHandler_initWithNSString_(self, type);
  self->flag_ = false;
}

ASCompassViewImpl_4 *new_ASCompassViewImpl_4_initWithASCompassViewImpl_withInt_withNSString_withNSString_(ASCompassViewImpl *outer$, int32_t capture$0, NSString *capture$1, NSString *type) {
  J2OBJC_NEW_IMPL(ASCompassViewImpl_4, initWithASCompassViewImpl_withInt_withNSString_withNSString_, outer$, capture$0, capture$1, type)
}

ASCompassViewImpl_4 *create_ASCompassViewImpl_4_initWithASCompassViewImpl_withInt_withNSString_withNSString_(ASCompassViewImpl *outer$, int32_t capture$0, NSString *capture$1, NSString *type) {
  J2OBJC_CREATE_IMPL(ASCompassViewImpl_4, initWithASCompassViewImpl_withInt_withNSString_withNSString_, outer$, capture$0, capture$1, type)
}

J2OBJC_INITIALIZED_DEFN(ASCompassViewImpl_$Lambda$1)

@implementation ASCompassViewImpl_$Lambda$1

- (id)applyWithId:(id<ASIWidget>)w {
  return new_ASCompassViewImpl_initWithASIWidget_(w);
}

- (id<JavaUtilFunctionFunction>)composeWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_composeWithJavaUtilFunctionFunction_(self, arg0);
}

- (id<JavaUtilFunctionFunction>)andThenWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_andThenWithJavaUtilFunctionFunction_(self, arg0);
}

+ (void)initialize {
  if (self == [ASCompassViewImpl_$Lambda$1 class]) {
    ASCompassViewImpl_$Lambda$1_instance = new_ASCompassViewImpl_$Lambda$1_init();
    J2OBJC_SET_INITIALIZED(ASCompassViewImpl_$Lambda$1)
  }
}

@end

void ASCompassViewImpl_$Lambda$1_init(ASCompassViewImpl_$Lambda$1 *self) {
  NSObject_init(self);
}

ASCompassViewImpl_$Lambda$1 *new_ASCompassViewImpl_$Lambda$1_init() {
  J2OBJC_NEW_IMPL(ASCompassViewImpl_$Lambda$1, init)
}

ASCompassViewImpl_$Lambda$1 *create_ASCompassViewImpl_$Lambda$1_init() {
  J2OBJC_CREATE_IMPL(ASCompassViewImpl_$Lambda$1, init)
}
