//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\com\ashera\spatialkit\CompassHelper.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CompassHelper")
#ifdef RESTRICT_CompassHelper
#define INCLUDE_ALL_CompassHelper 0
#else
#define INCLUDE_ALL_CompassHelper 1
#endif
#undef RESTRICT_CompassHelper

#if !defined (ASCompassHelper_) && (INCLUDE_ALL_CompassHelper || defined(INCLUDE_ASCompassHelper))
#define ASCompassHelper_

@class JavaLangDouble;
@class JavaLangFloat;

@interface ASCompassHelper : NSObject

#pragma mark Public

- (instancetype)init;

+ (float)calculateMagneticDeclinationWithDouble:(double)latitude
                                     withDouble:(double)longitude
                                     withDouble:(double)altitude;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCompassHelper)

FOUNDATION_EXPORT void ASCompassHelper_init(ASCompassHelper *self);

FOUNDATION_EXPORT ASCompassHelper *new_ASCompassHelper_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCompassHelper *create_ASCompassHelper_init(void);

FOUNDATION_EXPORT float ASCompassHelper_calculateMagneticDeclinationWithDouble_withDouble_withDouble_(double latitude, double longitude, double altitude);

J2OBJC_TYPE_LITERAL_HEADER(ASCompassHelper)

@compatibility_alias ComAsheraSpatialkitCompassHelper ASCompassHelper;


#endif

#pragma pop_macro("INCLUDE_ALL_CompassHelper")
