//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\com\ashera\spatialkit\CompassHelper.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "CompassHelper.h"
#include "J2ObjC_source.h"
#include "TSAGeoMag.h"
#include "java/lang/Double.h"
#include "java/lang/Float.h"
#include "java/util/GregorianCalendar.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@implementation ASCompassHelper

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCompassHelper_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (float)calculateMagneticDeclinationWithDouble:(double)latitude
                                     withDouble:(double)longitude
                                     withDouble:(double)altitude {
  return ASCompassHelper_calculateMagneticDeclinationWithDouble_withDouble_withDouble_(latitude, longitude, altitude);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "F", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(calculateMagneticDeclinationWithDouble:withDouble:withDouble:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "calculateMagneticDeclination", "DDD" };
  static const J2ObjcClassInfo _ASCompassHelper = { "CompassHelper", "com.ashera.spatialkit", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASCompassHelper;
}

@end

void ASCompassHelper_init(ASCompassHelper *self) {
  NSObject_init(self);
}

ASCompassHelper *new_ASCompassHelper_init() {
  J2OBJC_NEW_IMPL(ASCompassHelper, init)
}

ASCompassHelper *create_ASCompassHelper_init() {
  J2OBJC_CREATE_IMPL(ASCompassHelper, init)
}

float ASCompassHelper_calculateMagneticDeclinationWithDouble_withDouble_withDouble_(double latitude, double longitude, double altitude) {
  ASCompassHelper_initialize();
  ASTSAGeoMag *geoMag = new_ASTSAGeoMag_init();
  return (float) [geoMag getDeclinationWithDouble:latitude withDouble:longitude withDouble:[geoMag decimalYearWithJavaUtilGregorianCalendar:new_JavaUtilGregorianCalendar_init()] withDouble:altitude];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCompassHelper)

J2OBJC_NAME_MAPPING(ASCompassHelper, "com.ashera.spatialkit", "AS")
