//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\com\ashera\spatialkit\MapViewImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_MapViewImpl")
#ifdef RESTRICT_MapViewImpl
#define INCLUDE_ALL_MapViewImpl 0
#else
#define INCLUDE_ALL_MapViewImpl 1
#endif
#undef RESTRICT_MapViewImpl

#if !defined (ASMapViewImpl_) && (INCLUDE_ALL_MapViewImpl || defined(INCLUDE_ASMapViewImpl))
#define ASMapViewImpl_

#define RESTRICT_BaseWidget 1
#define INCLUDE_ASBaseWidget 1
#include "BaseWidget.h"

@class ASMapView;
@class ASMapViewImpl_LatLng;
@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASMapViewImpl : ASBaseWidget {
 @public
  id uiView_;
  ASMapView *measurableView_;
  id mapiView_;
}
@property id uiView;
@property id mapiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

+ (void)addEventInfoWithJavaUtilMap:(id<JavaUtilMap>)obj
           withASMapViewImpl_LatLng:(ASMapViewImpl_LatLng *)point;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)attributeName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (void)removeMarkerByIdWithNSString:(NSString *)id_;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

- (void)showMarkerForTarget;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(ASMapViewImpl)

J2OBJC_FIELD_SETTER(ASMapViewImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASMapViewImpl, measurableView_, ASMapView *)
J2OBJC_FIELD_SETTER(ASMapViewImpl, mapiView_, id)

inline NSString *ASMapViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASMapViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASMapViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASMapViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASMapViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASMapViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASMapViewImpl_init(ASMapViewImpl *self);

FOUNDATION_EXPORT ASMapViewImpl *new_ASMapViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMapViewImpl *create_ASMapViewImpl_init(void);

FOUNDATION_EXPORT void ASMapViewImpl_initWithNSString_(ASMapViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASMapViewImpl *new_ASMapViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMapViewImpl *create_ASMapViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASMapViewImpl_initWithNSString_withNSString_(ASMapViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASMapViewImpl *new_ASMapViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMapViewImpl *create_ASMapViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

FOUNDATION_EXPORT void ASMapViewImpl_addEventInfoWithJavaUtilMap_withASMapViewImpl_LatLng_(id<JavaUtilMap> obj, ASMapViewImpl_LatLng *point);

J2OBJC_TYPE_LITERAL_HEADER(ASMapViewImpl)

@compatibility_alias ComAsheraSpatialkitMapViewImpl ASMapViewImpl;


#endif

#if !defined (ASMapViewImpl_MapViewExt_) && (INCLUDE_ALL_MapViewImpl || defined(INCLUDE_ASMapViewImpl_MapViewExt))
#define ASMapViewImpl_MapViewExt_

#define RESTRICT_MapView 1
#define INCLUDE_ASMapView 1
#include "MapView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASMapViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASMapViewImpl_MapViewExt : ASMapView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASMapViewImpl:(ASMapViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMapViewImpl_MapViewExt)

FOUNDATION_EXPORT void ASMapViewImpl_MapViewExt_initWithASMapViewImpl_(ASMapViewImpl_MapViewExt *self, ASMapViewImpl *outer$);

FOUNDATION_EXPORT ASMapViewImpl_MapViewExt *new_ASMapViewImpl_MapViewExt_initWithASMapViewImpl_(ASMapViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMapViewImpl_MapViewExt *create_ASMapViewImpl_MapViewExt_initWithASMapViewImpl_(ASMapViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASMapViewImpl_MapViewExt)


#endif

#if !defined (ASMapViewImpl_MapLibreMap_) && (INCLUDE_ALL_MapViewImpl || defined(INCLUDE_ASMapViewImpl_MapLibreMap))
#define ASMapViewImpl_MapLibreMap_

@interface ASMapViewImpl_MapLibreMap : NSObject

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMapViewImpl_MapLibreMap)

FOUNDATION_EXPORT void ASMapViewImpl_MapLibreMap_init(ASMapViewImpl_MapLibreMap *self);

FOUNDATION_EXPORT ASMapViewImpl_MapLibreMap *new_ASMapViewImpl_MapLibreMap_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMapViewImpl_MapLibreMap *create_ASMapViewImpl_MapLibreMap_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMapViewImpl_MapLibreMap)


#endif

#if !defined (ASMapViewImpl_MapLibreMap_OnMapClickListener_) && (INCLUDE_ALL_MapViewImpl || defined(INCLUDE_ASMapViewImpl_MapLibreMap_OnMapClickListener))
#define ASMapViewImpl_MapLibreMap_OnMapClickListener_

@class ASMapViewImpl_LatLng;
@class JavaLangBoolean;

@protocol ASMapViewImpl_MapLibreMap_OnMapClickListener < JavaObject >

- (bool)onMapClickWithASMapViewImpl_LatLng:(ASMapViewImpl_LatLng *)point;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMapViewImpl_MapLibreMap_OnMapClickListener)

J2OBJC_TYPE_LITERAL_HEADER(ASMapViewImpl_MapLibreMap_OnMapClickListener)


#endif

#if !defined (ASMapViewImpl_LatLng_) && (INCLUDE_ALL_MapViewImpl || defined(INCLUDE_ASMapViewImpl_LatLng))
#define ASMapViewImpl_LatLng_

@class ASMapViewImpl;
@class JavaLangDouble;

@interface ASMapViewImpl_LatLng : NSObject

#pragma mark Public

- (instancetype)initWithASMapViewImpl:(ASMapViewImpl *)outer$
                           withDouble:(double)lat
                           withDouble:(double)lng;

- (double)getLatitude;

- (double)getLongitude;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMapViewImpl_LatLng)

FOUNDATION_EXPORT void ASMapViewImpl_LatLng_initWithASMapViewImpl_withDouble_withDouble_(ASMapViewImpl_LatLng *self, ASMapViewImpl *outer$, double lat, double lng);

FOUNDATION_EXPORT ASMapViewImpl_LatLng *new_ASMapViewImpl_LatLng_initWithASMapViewImpl_withDouble_withDouble_(ASMapViewImpl *outer$, double lat, double lng) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMapViewImpl_LatLng *create_ASMapViewImpl_LatLng_initWithASMapViewImpl_withDouble_withDouble_(ASMapViewImpl *outer$, double lat, double lng);

J2OBJC_TYPE_LITERAL_HEADER(ASMapViewImpl_LatLng)


#endif

#pragma pop_macro("INCLUDE_ALL_MapViewImpl")
