//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\org\maplibre\android\maps\MapView.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "FrameLayout.h"
#include "J2ObjC_source.h"
#include "MapView.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@implementation ASMapView

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASMapView_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASMapView = { "MapView", "org.maplibre.android.maps", NULL, methods, NULL, 7, 0x1, 1, 0, -1, -1, -1, -1, -1 };
  return &_ASMapView;
}

@end

void ASMapView_init(ASMapView *self) {
  ADFrameLayout_init(self);
}

ASMapView *new_ASMapView_init() {
  J2OBJC_NEW_IMPL(ASMapView, init)
}

ASMapView *create_ASMapView_init() {
  J2OBJC_CREATE_IMPL(ASMapView, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASMapView)

J2OBJC_NAME_MAPPING(ASMapView, "org.maplibre.android.maps", "AS")
