//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\com\ashera\spatialkit\MapViewImpl.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "BaseWidget.h"
#include "Drawable.h"
#include "EventCommand.h"
#include "EventCommandFactory.h"
#include "EventExpressionParser.h"
#include "HasWidgets.h"
#include "IActivity.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IListener.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "IWidget.h"
#include "IWidgetLifeCycleListener.h"
#include "J2ObjC_source.h"
#include "MapView.h"
#include "MapViewImpl.h"
#include "MeasureEvent.h"
#include "OnLayoutEvent.h"
#include "PluginInvoker.h"
#include "Rect.h"
#include "View.h"
#include "ViewImpl.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Double.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/lang/Runnable.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

#include "java/lang/Integer.h"
#include "java/lang/Float.h"
#include "java/lang/Boolean.h"
#include <UIKit/UIKit.h>
#include "HasLifeCycleDecorators.h"

#include "ASUIView.h"
#import <MapLibre/MapLibre.h>
#include "CustomPointAnnotation.h"


@class NSString;


#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface ASMapViewImpl () {
 @public
  id<ASMapViewImpl_MapLibreMap_OnMapClickListener> onMapClickListener_;
  bool addedOnMapClickListener_;
  id<JavaUtilMap> markerMap_;
  float lat_;
  float lng_;
  id targetLocationMarkerIcon_;
  NSString *targetLocationMarkerSnippet_;
  NSString *targetLocationMarkerTitle_;
  JavaLangBoolean *showMarkerForTarget_;
}

- (void)setWidgetOnNativeClass;

- (void)setOnMapClickListenerWithNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)createMLNMapView;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (void)releaseMLNMapView;

- (void)addMarkerWithId:(id)id_
                 withId:(id)latitude
                 withId:(id)longitude
                 withId:(id)title
                 withId:(id)snippet
                 withId:(id)icon;

- (void)removeMarkerWithId:(id)id_;

- (void)nativeremoveMarkerWithId:(id)marker;

- (void)setCameraTargetLngWithId:(id)objValue;

- (void)nativeSetCameraLatLngWithFloat:(float)lat
                             withFloat:(float)lng;

- (void)setCameraTargetLatWithId:(id)objValue;

- (void)setCameraZoomWithId:(id)objValue;

- (void)nativeSetCameraZoomWithInt:(int32_t)zoom;

- (void)setTargetLocationMarkerIconWithId:(id)objValue;

- (void)setTargetLocationMarkerSnippetWithId:(id)objValue;

- (void)setTargetLocationMarkerTitleWithId:(id)objValue;

- (void)showMarkerForTargetWithId:(id)objValue;

- (void)setCameraBearingWithId:(id)objValue;

- (void)nativeSetCameraBearingWithDouble:(double)bearing;

- (void)nativeSetCompassEnabledWithBoolean:(bool)enabled;

- (void)setUiCompassWithId:(id)objValue;

- (void)setUiCompassGravityWithId:(id)objValue;

- (void)nativeSetCompassPositionWithInt:(int32_t)gravity;

- (id)getImageWithNSString:(NSString *)imageName;

- (id)nativeAddMarkerWithDouble:(double)lat
                     withDouble:(double)lon
                   withNSString:(NSString *)title
                   withNSString:(NSString *)snippet
                   withNSString:(NSString *)imageName;

- (void)nativeMakeFrameForChildWidgetWithInt:(int32_t)l
                                     withInt:(int32_t)t
                                     withInt:(int32_t)r
                                     withInt:(int32_t)b;

- (void)setShowsUserLocationWithId:(id)objValue;

- (void)nativeShowsUserLocationWithBoolean:(bool)enabled;

- (void)setOnMapClickListener;

- (void)setOnMapClickListenerWithDouble:(double)lat
                             withDouble:(double)lng;

@end

J2OBJC_FIELD_SETTER(ASMapViewImpl, onMapClickListener_, id<ASMapViewImpl_MapLibreMap_OnMapClickListener>)
J2OBJC_FIELD_SETTER(ASMapViewImpl, markerMap_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ASMapViewImpl, targetLocationMarkerIcon_, id)
J2OBJC_FIELD_SETTER(ASMapViewImpl, targetLocationMarkerSnippet_, NSString *)
J2OBJC_FIELD_SETTER(ASMapViewImpl, targetLocationMarkerTitle_, NSString *)
J2OBJC_FIELD_SETTER(ASMapViewImpl, showMarkerForTarget_, JavaLangBoolean *)

inline int32_t ASMapViewImpl_get_Gravity_TOP(void);
#define ASMapViewImpl_Gravity_TOP 48
J2OBJC_STATIC_FIELD_CONSTANT(ASMapViewImpl, Gravity_TOP, int32_t)

inline int32_t ASMapViewImpl_get_Gravity_BOTTOM(void);
#define ASMapViewImpl_Gravity_BOTTOM 80
J2OBJC_STATIC_FIELD_CONSTANT(ASMapViewImpl, Gravity_BOTTOM, int32_t)

inline int32_t ASMapViewImpl_get_Gravity_LEFT(void);
#define ASMapViewImpl_Gravity_LEFT 3
J2OBJC_STATIC_FIELD_CONSTANT(ASMapViewImpl, Gravity_LEFT, int32_t)

inline int32_t ASMapViewImpl_get_Gravity_RIGHT(void);
#define ASMapViewImpl_Gravity_RIGHT 5
J2OBJC_STATIC_FIELD_CONSTANT(ASMapViewImpl, Gravity_RIGHT, int32_t)

__attribute__((unused)) static void ASMapViewImpl_setWidgetOnNativeClass(ASMapViewImpl *self);

__attribute__((unused)) static void ASMapViewImpl_setOnMapClickListenerWithNSString_withId_(ASMapViewImpl *self, NSString *strValue, id objValue);

__attribute__((unused)) static void ASMapViewImpl_createMLNMapView(ASMapViewImpl *self);

__attribute__((unused)) static void ASMapViewImpl_nativeCreateWithJavaUtilMap_(ASMapViewImpl *self, id<JavaUtilMap> params);

__attribute__((unused)) static void ASMapViewImpl_releaseMLNMapView(ASMapViewImpl *self);

__attribute__((unused)) static void ASMapViewImpl_addMarkerWithId_withId_withId_withId_withId_withId_(ASMapViewImpl *self, id id_, id latitude, id longitude, id title, id snippet, id icon);

__attribute__((unused)) static void ASMapViewImpl_removeMarkerWithId_(ASMapViewImpl *self, id id_);

__attribute__((unused)) static void ASMapViewImpl_nativeremoveMarkerWithId_(ASMapViewImpl *self, id marker);

__attribute__((unused)) static void ASMapViewImpl_setCameraTargetLngWithId_(ASMapViewImpl *self, id objValue);

__attribute__((unused)) static void ASMapViewImpl_nativeSetCameraLatLngWithFloat_withFloat_(ASMapViewImpl *self, float lat, float lng);

__attribute__((unused)) static void ASMapViewImpl_setCameraTargetLatWithId_(ASMapViewImpl *self, id objValue);

__attribute__((unused)) static void ASMapViewImpl_setCameraZoomWithId_(ASMapViewImpl *self, id objValue);

__attribute__((unused)) static void ASMapViewImpl_nativeSetCameraZoomWithInt_(ASMapViewImpl *self, int32_t zoom);

__attribute__((unused)) static void ASMapViewImpl_setTargetLocationMarkerIconWithId_(ASMapViewImpl *self, id objValue);

__attribute__((unused)) static void ASMapViewImpl_setTargetLocationMarkerSnippetWithId_(ASMapViewImpl *self, id objValue);

__attribute__((unused)) static void ASMapViewImpl_setTargetLocationMarkerTitleWithId_(ASMapViewImpl *self, id objValue);

__attribute__((unused)) static void ASMapViewImpl_showMarkerForTargetWithId_(ASMapViewImpl *self, id objValue);

__attribute__((unused)) static void ASMapViewImpl_setCameraBearingWithId_(ASMapViewImpl *self, id objValue);

__attribute__((unused)) static void ASMapViewImpl_nativeSetCameraBearingWithDouble_(ASMapViewImpl *self, double bearing);

__attribute__((unused)) static void ASMapViewImpl_nativeSetCompassEnabledWithBoolean_(ASMapViewImpl *self, bool enabled);

__attribute__((unused)) static void ASMapViewImpl_setUiCompassWithId_(ASMapViewImpl *self, id objValue);

__attribute__((unused)) static void ASMapViewImpl_setUiCompassGravityWithId_(ASMapViewImpl *self, id objValue);

__attribute__((unused)) static void ASMapViewImpl_nativeSetCompassPositionWithInt_(ASMapViewImpl *self, int32_t gravity);

__attribute__((unused)) static id ASMapViewImpl_getImageWithNSString_(ASMapViewImpl *self, NSString *imageName);

__attribute__((unused)) static id ASMapViewImpl_nativeAddMarkerWithDouble_withDouble_withNSString_withNSString_withNSString_(ASMapViewImpl *self, double lat, double lon, NSString *title, NSString *snippet, NSString *imageName);

__attribute__((unused)) static void ASMapViewImpl_nativeMakeFrameForChildWidgetWithInt_withInt_withInt_withInt_(ASMapViewImpl *self, int32_t l, int32_t t, int32_t r, int32_t b);

__attribute__((unused)) static void ASMapViewImpl_setShowsUserLocationWithId_(ASMapViewImpl *self, id objValue);

__attribute__((unused)) static void ASMapViewImpl_nativeShowsUserLocationWithBoolean_(ASMapViewImpl *self, bool enabled);

__attribute__((unused)) static void ASMapViewImpl_setOnMapClickListener(ASMapViewImpl *self);

__attribute__((unused)) static void ASMapViewImpl_setOnMapClickListenerWithDouble_withDouble_(ASMapViewImpl *self, double lat, double lng);

@interface ASMapViewImpl_MapViewExt () {
 @public
  WEAK_ ASMapViewImpl *this$0_;
  ASMeasureEvent *measureFinished_;
  ASOnLayoutEvent *onLayoutEvent_;
  id<JavaUtilList> overlays_;
  int32_t mMaxWidth_;
  int32_t mMaxHeight_;
  id<JavaUtilMap> templates_;
}

@end

J2OBJC_FIELD_SETTER(ASMapViewImpl_MapViewExt, measureFinished_, ASMeasureEvent *)
J2OBJC_FIELD_SETTER(ASMapViewImpl_MapViewExt, onLayoutEvent_, ASOnLayoutEvent *)
J2OBJC_FIELD_SETTER(ASMapViewImpl_MapViewExt, overlays_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ASMapViewImpl_MapViewExt, templates_, id<JavaUtilMap>)

@interface ASMapViewImpl_MapLibreMap_OnMapClickListener : NSObject

@end

@interface ASMapViewImpl_LatLng () {
 @public
  double lat_;
  double lng_;
}

@end

@interface ASMapViewImpl_OnMapClickListener : NSObject < ASMapViewImpl_MapLibreMap_OnMapClickListener, ASIListener > {
 @public
  id<ASIWidget> w_;
  ADView *view_;
  NSString *strValue_;
  NSString *action_;
}

- (NSString *)getAction;

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue;

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue
                     withNSString:(NSString *)action;

- (bool)onMapClickWithASMapViewImpl_LatLng:(ASMapViewImpl_LatLng *)point;

- (id<JavaUtilMap>)getOnMapClickEventObjWithASMapViewImpl_LatLng:(ASMapViewImpl_LatLng *)point;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMapViewImpl_OnMapClickListener)

J2OBJC_FIELD_SETTER(ASMapViewImpl_OnMapClickListener, w_, id<ASIWidget>)
J2OBJC_FIELD_SETTER(ASMapViewImpl_OnMapClickListener, view_, ADView *)
J2OBJC_FIELD_SETTER(ASMapViewImpl_OnMapClickListener, strValue_, NSString *)
J2OBJC_FIELD_SETTER(ASMapViewImpl_OnMapClickListener, action_, NSString *)

__attribute__((unused)) static void ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_(ASMapViewImpl_OnMapClickListener *self, id<ASIWidget> w, NSString *strValue);

__attribute__((unused)) static ASMapViewImpl_OnMapClickListener *new_ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASMapViewImpl_OnMapClickListener *create_ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue);

__attribute__((unused)) static void ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_withNSString_(ASMapViewImpl_OnMapClickListener *self, id<ASIWidget> w, NSString *strValue, NSString *action);

__attribute__((unused)) static ASMapViewImpl_OnMapClickListener *new_ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASMapViewImpl_OnMapClickListener *create_ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action);

J2OBJC_TYPE_LITERAL_HEADER(ASMapViewImpl_OnMapClickListener)


@interface ASMapViewImpl_MapViewDelloc : NSObject < JavaLangRunnable > {
 @public
  WEAK_ ASMapViewImpl *this$0_;
}

- (instancetype)initWithASMapViewImpl:(ASMapViewImpl *)outer$;

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMapViewImpl_MapViewDelloc)

__attribute__((unused)) static void ASMapViewImpl_MapViewDelloc_initWithASMapViewImpl_(ASMapViewImpl_MapViewDelloc *self, ASMapViewImpl *outer$);

__attribute__((unused)) static ASMapViewImpl_MapViewDelloc *new_ASMapViewImpl_MapViewDelloc_initWithASMapViewImpl_(ASMapViewImpl *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASMapViewImpl_MapViewDelloc *create_ASMapViewImpl_MapViewDelloc_initWithASMapViewImpl_(ASMapViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASMapViewImpl_MapViewDelloc)


NSString *ASMapViewImpl_LOCAL_NAME = @"org.maplibre.android.maps.MapView";
NSString *ASMapViewImpl_GROUP_NAME = @"org.maplibre.android.maps.MapView";

@implementation ASMapViewImpl

@synthesize uiView = uiView_;
@synthesize mapiView = mapiView_;

- (void)loadAttributesWithNSString:(NSString *)attributeName {
  ASViewImpl_register__WithNSString_(attributeName);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"maplibre_uiCompassGravity"])) withTypeWithNSString:@"gravity"])) withOrderWithInt:-1]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"maplibre_uiCompass"])) withTypeWithNSString:@"boolean"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"maplibre_cameraBearing"])) withTypeWithNSString:@"float"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"maplibre_cameraTargetLat"])) withTypeWithNSString:@"float"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"maplibre_cameraTargetLng"])) withTypeWithNSString:@"float"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"maplibre_cameraZoom"])) withTypeWithNSString:@"float"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"showMarkerForTarget"])) withTypeWithNSString:@"boolean"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"targetLocationMarkerTitle"])) withTypeWithNSString:@"resourcestring"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"targetLocationMarkerSnippet"])) withTypeWithNSString:@"resourcestring"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"targetLocationMarkerIcon"])) withTypeWithNSString:@"string"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"showsUserLocation"])) withTypeWithNSString:@"boolean"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"addMarker"])) withTypeWithNSString:@"object"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"removeMarker"])) withTypeWithNSString:@"string"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"onMapClick"])) withTypeWithNSString:@"string"]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASMapViewImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)localname {
  ASMapViewImpl_initWithNSString_(self, localname);
  return self;
}

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname {
  ASMapViewImpl_initWithNSString_withNSString_(self, groupName, localname);
  return self;
}

- (IOSClass *)getViewClass {
  return ASMapViewImpl_MapViewExt_class_();
}

- (id<ASIWidget>)newInstance {
  return new_ASMapViewImpl_initWithNSString_withNSString_(groupName_, localName_);
}

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params {
  [super createWithASIFragment:fragment withJavaUtilMap:params];
  measurableView_ = new_ASMapViewImpl_MapViewExt_initWithASMapViewImpl_(self);
  ASMapViewImpl_nativeCreateWithJavaUtilMap_(self, params);
  ASViewImpl_registerCommandConveterWithASIWidget_(self);
  ASMapViewImpl_setWidgetOnNativeClass(self);
}

- (void)setWidgetOnNativeClass {
  ASMapViewImpl_setWidgetOnNativeClass(self);
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id nativeWidget = [self asNativeWidget];
  ASViewImpl_setAttributeWithASIWidget_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"maplibre_uiCompassGravity", @"maplibre_uiCompass", @"maplibre_cameraBearing", @"maplibre_cameraTargetLat", @"maplibre_cameraTargetLng", @"maplibre_cameraZoom", @"showMarkerForTarget", @"targetLocationMarkerTitle", @"targetLocationMarkerSnippet", @"targetLocationMarkerIcon", @"showsUserLocation", @"addMarker", @"removeMarker", @"onMapClick" }, 14)) {
    case 0:
    {
      ASMapViewImpl_setUiCompassGravityWithId_(self, objValue);
    }
    break;
    case 1:
    {
      ASMapViewImpl_setUiCompassWithId_(self, objValue);
    }
    break;
    case 2:
    {
      ASMapViewImpl_setCameraBearingWithId_(self, objValue);
    }
    break;
    case 3:
    {
      ASMapViewImpl_setCameraTargetLatWithId_(self, objValue);
    }
    break;
    case 4:
    {
      ASMapViewImpl_setCameraTargetLngWithId_(self, objValue);
    }
    break;
    case 5:
    {
      ASMapViewImpl_setCameraZoomWithId_(self, objValue);
    }
    break;
    case 6:
    {
      ASMapViewImpl_showMarkerForTargetWithId_(self, objValue);
    }
    break;
    case 7:
    {
      ASMapViewImpl_setTargetLocationMarkerTitleWithId_(self, objValue);
    }
    break;
    case 8:
    {
      ASMapViewImpl_setTargetLocationMarkerSnippetWithId_(self, objValue);
    }
    break;
    case 9:
    {
      ASMapViewImpl_setTargetLocationMarkerIconWithId_(self, objValue);
    }
    break;
    case 10:
    {
      ASMapViewImpl_setShowsUserLocationWithId_(self, objValue);
    }
    break;
    case 11:
    {
      if ([JavaUtilMap_class_() isInstance:objValue]) {
        id<JavaUtilMap> data = ((id<JavaUtilMap>) cast_check(objValue, JavaUtilMap_class_()));
        id id_ = [self quickConvertWithId:[((id<JavaUtilMap>) nil_chk(data)) getWithId:@"id"] withNSString:@"string"];
        id latitude = [self quickConvertWithId:[data getWithId:@"latitude"] withNSString:@"float"];
        id longitude = [self quickConvertWithId:[data getWithId:@"longitude"] withNSString:@"float"];
        id title = [self quickConvertWithId:[data getWithId:@"title"] withNSString:@"resourcestring"];
        id snippet = [self quickConvertWithId:[data getWithId:@"snippet"] withNSString:@"resourcestring"];
        id icon = [self quickConvertWithId:[data getWithId:@"icon"] withNSString:@"string"];
        ASMapViewImpl_addMarkerWithId_withId_withId_withId_withId_withId_(self, id_, latitude, longitude, title, snippet, icon);
      }
      if ([JavaUtilList_class_() isInstance:objValue]) {
        id<JavaUtilList> list = (id<JavaUtilList>) cast_check(objValue, JavaUtilList_class_());
        for (id __strong object in nil_chk(list)) {
          id<JavaUtilMap> data = ASPluginInvoker_getMapWithId_(object);
          id id_ = [self quickConvertWithId:[((id<JavaUtilMap>) nil_chk(data)) getWithId:@"id"] withNSString:@"string"];
          id latitude = [self quickConvertWithId:[data getWithId:@"latitude"] withNSString:@"float"];
          id longitude = [self quickConvertWithId:[data getWithId:@"longitude"] withNSString:@"float"];
          id title = [self quickConvertWithId:[data getWithId:@"title"] withNSString:@"resourcestring"];
          id snippet = [self quickConvertWithId:[data getWithId:@"snippet"] withNSString:@"resourcestring"];
          id icon = [self quickConvertWithId:[data getWithId:@"icon"] withNSString:@"string"];
          ASMapViewImpl_addMarkerWithId_withId_withId_withId_withId_withId_(self, id_, latitude, longitude, title, snippet, icon);
        }
      }
    }
    break;
    case 12:
    {
      ASMapViewImpl_removeMarkerWithId_(self, objValue);
    }
    break;
    case 13:
    {
      ASMapViewImpl_setOnMapClickListenerWithNSString_withId_(self, strValue, objValue);
    }
    break;
    default:
    break;
  }
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id nativeWidget = [self asNativeWidget];
  id attributeValue = ASViewImpl_getAttributeWithASIWidget_withId_withASWidgetAttribute_withASILifeCycleDecorator_(self, nativeWidget, key, decorator);
  if (attributeValue != nil) {
    return attributeValue;
  }
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){  }, 0)) {
  }
  return nil;
}

- (id)asWidget {
  return measurableView_;
}

- (void)setOnMapClickListenerWithNSString:(NSString *)strValue
                                   withId:(id)objValue {
  ASMapViewImpl_setOnMapClickListenerWithNSString_withId_(self, strValue, objValue);
}

+ (void)addEventInfoWithJavaUtilMap:(id<JavaUtilMap>)obj
           withASMapViewImpl_LatLng:(ASMapViewImpl_LatLng *)point {
  ASMapViewImpl_addEventInfoWithJavaUtilMap_withASMapViewImpl_LatLng_(obj, point);
}

- (id)asNativeWidget {
  return uiView_;
}

- (bool)checkIosVersionWithNSString:(NSString *)v {
  return ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending);
}

- (void)setIdWithNSString:(NSString *)id_ {
  if (id_ != nil && ![id_ isEqual:@""]) {
    [super setIdWithNSString:id_];
    [((ASMapView *) nil_chk(measurableView_)) setIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([self quickConvertWithId:id_ withNSString:@"id"], [JavaLangInteger class]))) intValue]];
  }
}

- (void)setVisibleWithBoolean:(bool)b {
  [((ADView *) nil_chk(((ADView *) cast_chk([self asWidget], [ADView class])))) setVisibilityWithInt:b ? ADView_VISIBLE : ADView_GONE];
}

- (void)requestLayout {
  if ([self isInitialised]) {
    ASViewImpl_requestLayoutWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)invalidate {
  if ([self isInitialised]) {
    ASViewImpl_invalidateWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)createMLNMapView {
  ASMapViewImpl_createMLNMapView(self);
}

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASMapViewImpl_nativeCreateWithJavaUtilMap_(self, params);
}

- (void)releaseMLNMapView {
  ASMapViewImpl_releaseMLNMapView(self);
}

- (void)addMarkerWithId:(id)id_
                 withId:(id)latitude
                 withId:(id)longitude
                 withId:(id)title
                 withId:(id)snippet
                 withId:(id)icon {
  ASMapViewImpl_addMarkerWithId_withId_withId_withId_withId_withId_(self, id_, latitude, longitude, title, snippet, icon);
}

- (void)removeMarkerWithId:(id)id_ {
  ASMapViewImpl_removeMarkerWithId_(self, id_);
}

- (void)removeMarkerByIdWithNSString:(NSString *)id_ {
  if (markerMap_ != nil && [markerMap_ containsKeyWithId:id_]) {
    id marker = [markerMap_ getWithId:id_];
    if (marker != nil) {
      ASMapViewImpl_nativeremoveMarkerWithId_(self, marker);
      (void) [((id<JavaUtilMap>) nil_chk(markerMap_)) removeWithId:id_];
    }
  }
}

- (void)nativeremoveMarkerWithId:(id)marker {
  ASMapViewImpl_nativeremoveMarkerWithId_(self, marker);
}

- (void)setCameraTargetLngWithId:(id)objValue {
  ASMapViewImpl_setCameraTargetLngWithId_(self, objValue);
}

- (void)nativeSetCameraLatLngWithFloat:(float)lat
                             withFloat:(float)lng {
  ASMapViewImpl_nativeSetCameraLatLngWithFloat_withFloat_(self, lat, lng);
}

- (void)setCameraTargetLatWithId:(id)objValue {
  ASMapViewImpl_setCameraTargetLatWithId_(self, objValue);
}

- (void)setCameraZoomWithId:(id)objValue {
  ASMapViewImpl_setCameraZoomWithId_(self, objValue);
}

- (void)nativeSetCameraZoomWithInt:(int32_t)zoom {
  ASMapViewImpl_nativeSetCameraZoomWithInt_(self, zoom);
}

- (void)setTargetLocationMarkerIconWithId:(id)objValue {
  ASMapViewImpl_setTargetLocationMarkerIconWithId_(self, objValue);
}

- (void)setTargetLocationMarkerSnippetWithId:(id)objValue {
  ASMapViewImpl_setTargetLocationMarkerSnippetWithId_(self, objValue);
}

- (void)setTargetLocationMarkerTitleWithId:(id)objValue {
  ASMapViewImpl_setTargetLocationMarkerTitleWithId_(self, objValue);
}

- (void)showMarkerForTargetWithId:(id)objValue {
  ASMapViewImpl_showMarkerForTargetWithId_(self, objValue);
}

- (void)setCameraBearingWithId:(id)objValue {
  ASMapViewImpl_setCameraBearingWithId_(self, objValue);
}

- (void)nativeSetCameraBearingWithDouble:(double)bearing {
  ASMapViewImpl_nativeSetCameraBearingWithDouble_(self, bearing);
}

- (void)nativeSetCompassEnabledWithBoolean:(bool)enabled {
  ASMapViewImpl_nativeSetCompassEnabledWithBoolean_(self, enabled);
}

- (void)setUiCompassWithId:(id)objValue {
  ASMapViewImpl_setUiCompassWithId_(self, objValue);
}

- (void)setUiCompassGravityWithId:(id)objValue {
  ASMapViewImpl_setUiCompassGravityWithId_(self, objValue);
}

- (void)nativeSetCompassPositionWithInt:(int32_t)gravity {
  ASMapViewImpl_nativeSetCompassPositionWithInt_(self, gravity);
}

- (void)mapView:(MLNMapView *)mapView didFinishLoadingStyle:(MLNStyle *)style {
}

- (void)mapView:(MLNMapView *)mapView didTapAtCoordinate:(CLLocationCoordinate2D)coordinate {
  double lat = coordinate.latitude;
  double lng = coordinate.longitude;
  [self setOnMapClickListenerWithDouble: lat withDouble: lng];
}

- (BOOL)mapView:(MLNMapView *)mapView annotationCanShowCallout:(id<MLNAnnotation>)annotation {
  if (![annotation isKindOfClass:[CustomPointAnnotation class]]) {
    return NO;
  }
  
  CustomPointAnnotation *ann = (CustomPointAnnotation *)annotation;
  return ann.title != nil;
}

- (MLNAnnotationView *)mapView:(MLNMapView *)mapView
viewForAnnotation:(id<MLNAnnotation>)annotation {
  
  if (![annotation isKindOfClass:[CustomPointAnnotation class]]) {
    return nil;
  }
  
  CustomPointAnnotation *ann = (CustomPointAnnotation *)annotation;
  
  if (!ann.imageName) {
    return nil;
  }
  
  NSString *reuseId = ann.imageName;
  MLNAnnotationView *view =
  [mapView dequeueReusableAnnotationViewWithIdentifier:reuseId];
  
  UIImage *image = nil;
  id imgObj = [self getImageWithNSString:ann.imageName]; // J2ObjC naming
  
  if ([imgObj isKindOfClass:[UIImage class]]) {
    image = (UIImage *)imgObj;
  }
  
  if (!image) return nil;
  
  CGSize size = image.size;
  
  UIImageView *img;
  
  if (!view) {
    view = [[MLNAnnotationView alloc] initWithReuseIdentifier:reuseId];
    
    img = [[UIImageView alloc] initWithImage:image];
    img.tag = 100;
    
    img.frame = CGRectMake(0, 0, size.width, size.height);
    
    [view addSubview:img];
    view.frame = img.frame;
  } else {
    img = [view viewWithTag:100];
    img.image = image;
    img.frame = CGRectMake(0, 0, size.width, size.height);
    view.frame = img.frame;
  }
  
  view.centerOffset = CGVectorMake(0, -size.height / 2.0);
  
  return view;
}

- (id)getImageWithNSString:(NSString *)imageName {
  return ASMapViewImpl_getImageWithNSString_(self, imageName);
}

- (id)nativeAddMarkerWithDouble:(double)lat
                     withDouble:(double)lon
                   withNSString:(NSString *)title
                   withNSString:(NSString *)snippet
                   withNSString:(NSString *)imageName {
  return ASMapViewImpl_nativeAddMarkerWithDouble_withDouble_withNSString_withNSString_withNSString_(self, lat, lon, title, snippet, imageName);
}

- (void)initialized {
  [super initialized];
  [self showMarkerForTarget];
}

- (void)showMarkerForTarget {
  [self removeMarkerByIdWithNSString:@"targetLocationMarker"];
  if (showMarkerForTarget_ != nil && [showMarkerForTarget_ booleanValue]) {
    ASMapViewImpl_addMarkerWithId_withId_withId_withId_withId_withId_(self, @"targetLocationMarker", JavaLangFloat_valueOfWithFloat_(lat_), JavaLangFloat_valueOfWithFloat_(lng_), targetLocationMarkerTitle_, targetLocationMarkerSnippet_, targetLocationMarkerIcon_);
  }
}

- (void)nativeMakeFrameForChildWidgetWithInt:(int32_t)l
                                     withInt:(int32_t)t
                                     withInt:(int32_t)r
                                     withInt:(int32_t)b {
  ASMapViewImpl_nativeMakeFrameForChildWidgetWithInt_withInt_withInt_withInt_(self, l, t, r, b);
}

- (void)setShowsUserLocationWithId:(id)objValue {
  ASMapViewImpl_setShowsUserLocationWithId_(self, objValue);
}

- (void)nativeShowsUserLocationWithBoolean:(bool)enabled {
  ASMapViewImpl_nativeShowsUserLocationWithBoolean_(self, enabled);
}

- (void)setOnMapClickListener {
  ASMapViewImpl_setOnMapClickListener(self);
}

- (void)setOnMapClickListenerWithDouble:(double)lat
                             withDouble:(double)lng {
  ASMapViewImpl_setOnMapClickListenerWithDouble_withDouble_(self, lat, lng);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 8, 9, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 10, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 12, 13, -1, 14, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 15, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 16, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 17, 18, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 19, 20, -1, 21, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 22, 23, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 24, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 27, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 28, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 29, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 31, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 32, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 33, 34, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 35, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 36, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 37, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 38, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 39, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 40, 41, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 42, 18, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 43, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 44, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 45, 34, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, 46, 1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x102, 47, 48, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 49, 50, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 51, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 52, 18, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 10, 53, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(loadAttributesWithNSString:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(initWithNSString:withNSString:);
  methods[4].selector = @selector(getViewClass);
  methods[5].selector = @selector(newInstance);
  methods[6].selector = @selector(createWithASIFragment:withJavaUtilMap:);
  methods[7].selector = @selector(setWidgetOnNativeClass);
  methods[8].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[9].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[10].selector = @selector(asWidget);
  methods[11].selector = @selector(setOnMapClickListenerWithNSString:withId:);
  methods[12].selector = @selector(addEventInfoWithJavaUtilMap:withASMapViewImpl_LatLng:);
  methods[13].selector = @selector(asNativeWidget);
  methods[14].selector = @selector(checkIosVersionWithNSString:);
  methods[15].selector = @selector(setIdWithNSString:);
  methods[16].selector = @selector(setVisibleWithBoolean:);
  methods[17].selector = @selector(requestLayout);
  methods[18].selector = @selector(invalidate);
  methods[19].selector = @selector(createMLNMapView);
  methods[20].selector = @selector(nativeCreateWithJavaUtilMap:);
  methods[21].selector = @selector(releaseMLNMapView);
  methods[22].selector = @selector(addMarkerWithId:withId:withId:withId:withId:withId:);
  methods[23].selector = @selector(removeMarkerWithId:);
  methods[24].selector = @selector(removeMarkerByIdWithNSString:);
  methods[25].selector = @selector(nativeremoveMarkerWithId:);
  methods[26].selector = @selector(setCameraTargetLngWithId:);
  methods[27].selector = @selector(nativeSetCameraLatLngWithFloat:withFloat:);
  methods[28].selector = @selector(setCameraTargetLatWithId:);
  methods[29].selector = @selector(setCameraZoomWithId:);
  methods[30].selector = @selector(nativeSetCameraZoomWithInt:);
  methods[31].selector = @selector(setTargetLocationMarkerIconWithId:);
  methods[32].selector = @selector(setTargetLocationMarkerSnippetWithId:);
  methods[33].selector = @selector(setTargetLocationMarkerTitleWithId:);
  methods[34].selector = @selector(showMarkerForTargetWithId:);
  methods[35].selector = @selector(setCameraBearingWithId:);
  methods[36].selector = @selector(nativeSetCameraBearingWithDouble:);
  methods[37].selector = @selector(nativeSetCompassEnabledWithBoolean:);
  methods[38].selector = @selector(setUiCompassWithId:);
  methods[39].selector = @selector(setUiCompassGravityWithId:);
  methods[40].selector = @selector(nativeSetCompassPositionWithInt:);
  methods[41].selector = @selector(getImageWithNSString:);
  methods[42].selector = @selector(nativeAddMarkerWithDouble:withDouble:withNSString:withNSString:withNSString:);
  methods[43].selector = @selector(initialized);
  methods[44].selector = @selector(showMarkerForTarget);
  methods[45].selector = @selector(nativeMakeFrameForChildWidgetWithInt:withInt:withInt:withInt:);
  methods[46].selector = @selector(setShowsUserLocationWithId:);
  methods[47].selector = @selector(nativeShowsUserLocationWithBoolean:);
  methods[48].selector = @selector(setOnMapClickListener);
  methods[49].selector = @selector(setOnMapClickListenerWithDouble:withDouble:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 54, -1, -1 },
    { "GROUP_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 55, -1, -1 },
    { "uiView_", "LNSObject;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "measurableView_", "LASMapView;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "onMapClickListener_", "LASMapViewImpl_MapLibreMap_OnMapClickListener;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "addedOnMapClickListener_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mapiView_", "LNSObject;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "markerMap_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 56, -1 },
    { "lat_", "F", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "lng_", "F", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "targetLocationMarkerIcon_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "targetLocationMarkerSnippet_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "targetLocationMarkerTitle_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "showMarkerForTarget_", "LJavaLangBoolean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "Gravity_TOP", "I", .constantValue.asInt = ASMapViewImpl_Gravity_TOP, 0x1a, -1, -1, -1, -1 },
    { "Gravity_BOTTOM", "I", .constantValue.asInt = ASMapViewImpl_Gravity_BOTTOM, 0x1a, -1, -1, -1, -1 },
    { "Gravity_LEFT", "I", .constantValue.asInt = ASMapViewImpl_Gravity_LEFT, 0x1a, -1, -1, -1, -1 },
    { "Gravity_RIGHT", "I", .constantValue.asInt = ASMapViewImpl_Gravity_RIGHT, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "loadAttributes", "LNSString;", "LNSString;LNSString;", "create", "LASIFragment;LJavaUtilMap;", "(Lcom/ashera/core/IFragment;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "setOnMapClickListener", "LNSString;LNSObject;", "addEventInfo", "LJavaUtilMap;LASMapViewImpl_LatLng;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;Lcom/ashera/spatialkit/MapViewImpl$LatLng;)V", "checkIosVersion", "setId", "setVisible", "Z", "nativeCreate", "LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "addMarker", "LNSObject;LNSObject;LNSObject;LNSObject;LNSObject;LNSObject;", "removeMarker", "LNSObject;", "removeMarkerById", "nativeremoveMarker", "setCameraTargetLng", "nativeSetCameraLatLng", "FF", "setCameraTargetLat", "setCameraZoom", "nativeSetCameraZoom", "I", "setTargetLocationMarkerIcon", "setTargetLocationMarkerSnippet", "setTargetLocationMarkerTitle", "showMarkerForTarget", "setCameraBearing", "nativeSetCameraBearing", "D", "nativeSetCompassEnabled", "setUiCompass", "setUiCompassGravity", "nativeSetCompassPosition", "getImage", "nativeAddMarker", "DDLNSString;LNSString;LNSString;", "nativeMakeFrameForChildWidget", "IIII", "setShowsUserLocation", "nativeShowsUserLocation", "DD", &ASMapViewImpl_LOCAL_NAME, &ASMapViewImpl_GROUP_NAME, "Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;", "LASMapViewImpl_MapViewExt;LASMapViewImpl_MapLibreMap;LASMapViewImpl_LatLng;LASMapViewImpl_OnMapClickListener;LASMapViewImpl_MapViewDelloc;" };
  static const J2ObjcClassInfo _ASMapViewImpl = { "MapViewImpl", "com.ashera.spatialkit", ptrTable, methods, fields, 7, 0x1, 50, 18, -1, 57, -1, -1, -1 };
  return &_ASMapViewImpl;
}

@end

void ASMapViewImpl_init(ASMapViewImpl *self) {
  ASBaseWidget_initWithNSString_withNSString_(self, ASMapViewImpl_GROUP_NAME, ASMapViewImpl_LOCAL_NAME);
}

ASMapViewImpl *new_ASMapViewImpl_init() {
  J2OBJC_NEW_IMPL(ASMapViewImpl, init)
}

ASMapViewImpl *create_ASMapViewImpl_init() {
  J2OBJC_CREATE_IMPL(ASMapViewImpl, init)
}

void ASMapViewImpl_initWithNSString_(ASMapViewImpl *self, NSString *localname) {
  ASBaseWidget_initWithNSString_withNSString_(self, ASMapViewImpl_GROUP_NAME, localname);
}

ASMapViewImpl *new_ASMapViewImpl_initWithNSString_(NSString *localname) {
  J2OBJC_NEW_IMPL(ASMapViewImpl, initWithNSString_, localname)
}

ASMapViewImpl *create_ASMapViewImpl_initWithNSString_(NSString *localname) {
  J2OBJC_CREATE_IMPL(ASMapViewImpl, initWithNSString_, localname)
}

void ASMapViewImpl_initWithNSString_withNSString_(ASMapViewImpl *self, NSString *groupName, NSString *localname) {
  ASBaseWidget_initWithNSString_withNSString_(self, groupName, localname);
}

ASMapViewImpl *new_ASMapViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_NEW_IMPL(ASMapViewImpl, initWithNSString_withNSString_, groupName, localname)
}

ASMapViewImpl *create_ASMapViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_CREATE_IMPL(ASMapViewImpl, initWithNSString_withNSString_, groupName, localname)
}

void ASMapViewImpl_setWidgetOnNativeClass(ASMapViewImpl *self) {
  ((ASUIView*) self.uiView).widget = self;
}

void ASMapViewImpl_setOnMapClickListenerWithNSString_withId_(ASMapViewImpl *self, NSString *strValue, id objValue) {
  if ([objValue isKindOfClass:[NSString class]]) {
    self->onMapClickListener_ = new_ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_(self, strValue);
  }
  else {
    self->onMapClickListener_ = (id<ASMapViewImpl_MapLibreMap_OnMapClickListener>) cast_check(objValue, ASMapViewImpl_MapLibreMap_OnMapClickListener_class_());
  }
  ASMapViewImpl_setOnMapClickListener(self);
}

void ASMapViewImpl_addEventInfoWithJavaUtilMap_withASMapViewImpl_LatLng_(id<JavaUtilMap> obj, ASMapViewImpl_LatLng *point) {
  ASMapViewImpl_initialize();
  (void) [((id<JavaUtilMap>) nil_chk(obj)) putWithId:@"latitude" withId:JavaLangDouble_valueOfWithDouble_([((ASMapViewImpl_LatLng *) nil_chk(point)) getLatitude])];
  (void) [obj putWithId:@"longitude" withId:JavaLangDouble_valueOfWithDouble_([point getLongitude])];
}

void ASMapViewImpl_createMLNMapView(ASMapViewImpl *self) {
  ASUIView* uiView = [ASUIView new];
  uiView.backgroundColor = [UIColor clearColor];
  self->uiView_ = uiView;
  
  NSURL *styleURL = [NSURL URLWithString:@"https://tiles.openfreemap.org/styles/liberty"];
  MLNMapView* mapView= [[MLNMapView alloc] initWithFrame:CGRectZero
  styleURL:styleURL];
  mapView.delegate = self;
  self->mapiView_ = mapView;
  [uiView addSubview: mapView];
}

void ASMapViewImpl_nativeCreateWithJavaUtilMap_(ASMapViewImpl *self, id<JavaUtilMap> params) {
  ASMapViewImpl_createMLNMapView(self);
  [((id<ASIFragment>) nil_chk(self->fragment_)) addDisposableWithId:new_ASMapViewImpl_MapViewDelloc_initWithASMapViewImpl_(self)];
}

void ASMapViewImpl_releaseMLNMapView(ASMapViewImpl *self) {
  MLNMapView* mapView = (MLNMapView*)self->mapiView_;
  mapView.showsUserLocation = NO;
  mapView.delegate = nil;
  [mapView removeFromSuperview];
  self->mapiView_ = nil;
}

void ASMapViewImpl_addMarkerWithId_withId_withId_withId_withId_withId_(ASMapViewImpl *self, id id_, id latitude, id longitude, id title, id snippet, id icon) {
  [self removeMarkerByIdWithNSString:(NSString *) cast_chk(id_, [NSString class])];
  if (self->markerMap_ == nil) {
    self->markerMap_ = new_JavaUtilHashMap_init();
  }
  id marker = ASMapViewImpl_nativeAddMarkerWithDouble_withDouble_withNSString_withNSString_withNSString_(self, [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(latitude, [JavaLangFloat class]))) floatValue], [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(longitude, [JavaLangFloat class]))) floatValue], (NSString *) cast_chk(title, [NSString class]), (NSString *) cast_chk(snippet, [NSString class]), (NSString *) cast_chk(icon, [NSString class]));
  (void) [((id<JavaUtilMap>) nil_chk(self->markerMap_)) putWithId:(NSString *) cast_chk(id_, [NSString class]) withId:marker];
}

void ASMapViewImpl_removeMarkerWithId_(ASMapViewImpl *self, id id_) {
  [self removeMarkerByIdWithNSString:(NSString *) cast_chk(id_, [NSString class])];
}

void ASMapViewImpl_nativeremoveMarkerWithId_(ASMapViewImpl *self, id marker) {
  MLNMapView* mapView = (MLNMapView*)self->mapiView_;
  CustomPointAnnotation *ann = (CustomPointAnnotation*) marker;
  [mapView removeAnnotation:ann];
}

void ASMapViewImpl_setCameraTargetLngWithId_(ASMapViewImpl *self, id objValue) {
  self->lng_ = [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class]))) floatValue];
  ASMapViewImpl_nativeSetCameraLatLngWithFloat_withFloat_(self, self->lat_, self->lng_);
  if ([self isInitialised]) {
    [self showMarkerForTarget];
  }
}

void ASMapViewImpl_nativeSetCameraLatLngWithFloat_withFloat_(ASMapViewImpl *self, float lat, float lng) {
  CLLocationCoordinate2D coord = CLLocationCoordinate2DMake(lat, lng);
  MLNMapView* mapView = (MLNMapView*)self->mapiView_;
  [mapView setCenterCoordinate:coord animated:NO];
}

void ASMapViewImpl_setCameraTargetLatWithId_(ASMapViewImpl *self, id objValue) {
  self->lat_ = [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class]))) floatValue];
  ASMapViewImpl_nativeSetCameraLatLngWithFloat_withFloat_(self, self->lat_, self->lng_);
  if ([self isInitialised]) {
    [self showMarkerForTarget];
  }
}

void ASMapViewImpl_setCameraZoomWithId_(ASMapViewImpl *self, id objValue) {
  ASMapViewImpl_nativeSetCameraZoomWithInt_(self, [((JavaLangFloat *) nil_chk(((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class])))) intValue]);
}

void ASMapViewImpl_nativeSetCameraZoomWithInt_(ASMapViewImpl *self, int32_t zoom) {
  MLNMapView* mapView = (MLNMapView*)self->mapiView_;
  [mapView setZoomLevel:zoom animated:NO];
}

void ASMapViewImpl_setTargetLocationMarkerIconWithId_(ASMapViewImpl *self, id objValue) {
  self->targetLocationMarkerIcon_ = objValue;
  if ([self isInitialised]) {
    [self showMarkerForTarget];
  }
}

void ASMapViewImpl_setTargetLocationMarkerSnippetWithId_(ASMapViewImpl *self, id objValue) {
  self->targetLocationMarkerSnippet_ = (NSString *) cast_chk(objValue, [NSString class]);
  if ([self isInitialised]) {
    [self showMarkerForTarget];
  }
}

void ASMapViewImpl_setTargetLocationMarkerTitleWithId_(ASMapViewImpl *self, id objValue) {
  self->targetLocationMarkerTitle_ = (NSString *) cast_chk(objValue, [NSString class]);
  if ([self isInitialised]) {
    [self showMarkerForTarget];
  }
}

void ASMapViewImpl_showMarkerForTargetWithId_(ASMapViewImpl *self, id objValue) {
  self->showMarkerForTarget_ = (JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]);
  if ([self isInitialised]) {
    [self showMarkerForTarget];
  }
}

void ASMapViewImpl_setCameraBearingWithId_(ASMapViewImpl *self, id objValue) {
  ASMapViewImpl_nativeSetCameraBearingWithDouble_(self, [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class]))) floatValue]);
}

void ASMapViewImpl_nativeSetCameraBearingWithDouble_(ASMapViewImpl *self, double bearing) {
  MLNMapView* mapView = (MLNMapView*)self->mapiView_;
  [mapView setDirection:bearing animated:NO];
}

void ASMapViewImpl_nativeSetCompassEnabledWithBoolean_(ASMapViewImpl *self, bool enabled) {
  MLNMapView* mapView = (MLNMapView*)self->mapiView_;
  mapView.showsCompassView = enabled;
}

void ASMapViewImpl_setUiCompassWithId_(ASMapViewImpl *self, id objValue) {
  bool enabled = [((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue];
  ASMapViewImpl_nativeSetCompassEnabledWithBoolean_(self, enabled);
}

void ASMapViewImpl_setUiCompassGravityWithId_(ASMapViewImpl *self, id objValue) {
  ASMapViewImpl_nativeSetCompassPositionWithInt_(self, [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]);
}

void ASMapViewImpl_nativeSetCompassPositionWithInt_(ASMapViewImpl *self, int32_t gravity) {
  MLNMapView* mapView = (MLNMapView*)self->mapiView_;
  
  MLNOrnamentPosition position = MLNOrnamentPositionTopRight;
  
  BOOL isTop = (gravity & ASMapViewImpl_Gravity_TOP) == ASMapViewImpl_Gravity_TOP;
  BOOL isBottom = (gravity & ASMapViewImpl_Gravity_BOTTOM) == ASMapViewImpl_Gravity_BOTTOM;
  BOOL isLeft = (gravity & ASMapViewImpl_Gravity_LEFT) == ASMapViewImpl_Gravity_LEFT;
  BOOL isRight = (gravity & ASMapViewImpl_Gravity_RIGHT) == ASMapViewImpl_Gravity_RIGHT;
  
  if (isTop && isLeft) {
    position = MLNOrnamentPositionTopLeft;
  } else if (isTop && isRight) {
    position = MLNOrnamentPositionTopRight;
  } else if (isBottom && isLeft) {
    position = MLNOrnamentPositionBottomLeft;
  } else if (isBottom && isRight) {
    position = MLNOrnamentPositionBottomRight;
  }
  
  mapView.compassViewPosition = position;
}

id ASMapViewImpl_getImageWithNSString_(ASMapViewImpl *self, NSString *imageName) {
  id drawable = [self quickConvertWithId:imageName withNSString:@"drawable"];
  if ([drawable isKindOfClass:[ADDrawable class]]) {
    drawable = [((ADDrawable *) nil_chk(((ADDrawable *) drawable))) getDrawable];
  }
  return drawable;
}

id ASMapViewImpl_nativeAddMarkerWithDouble_withDouble_withNSString_withNSString_withNSString_(ASMapViewImpl *self, double lat, double lon, NSString *title, NSString *snippet, NSString *imageName) {
  MLNMapView* mapView = (MLNMapView*)self->mapiView_;
  
  CustomPointAnnotation *ann = [[CustomPointAnnotation alloc] init];
  ann.coordinate = CLLocationCoordinate2DMake(lat, lon);
  ann.title = title;
  ann.subtitle = snippet;
  ann.imageName = imageName;
  
  [mapView addAnnotation:ann];
  return ann;
}

void ASMapViewImpl_nativeMakeFrameForChildWidgetWithInt_withInt_withInt_withInt_(ASMapViewImpl *self, int32_t l, int32_t t, int32_t r, int32_t b) {
  ASViewImpl_updateBoundsWithId_withInt_withInt_withInt_withInt_(self->mapiView_, 0, 0, r - l, b - t);
}

void ASMapViewImpl_setShowsUserLocationWithId_(ASMapViewImpl *self, id objValue) {
  ASMapViewImpl_nativeShowsUserLocationWithBoolean_(self, [((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue]);
}

void ASMapViewImpl_nativeShowsUserLocationWithBoolean_(ASMapViewImpl *self, bool enabled) {
  MLNMapView* mapView = (MLNMapView*)self->mapiView_;
  mapView.showsUserLocation = enabled;
}

void ASMapViewImpl_setOnMapClickListener(ASMapViewImpl *self) {
}

void ASMapViewImpl_setOnMapClickListenerWithDouble_withDouble_(ASMapViewImpl *self, double lat, double lng) {
  if (self->onMapClickListener_ != nil) {
    [self->onMapClickListener_ onMapClickWithASMapViewImpl_LatLng:new_ASMapViewImpl_LatLng_initWithASMapViewImpl_withDouble_withDouble_(self, lat, lng)];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASMapViewImpl)

J2OBJC_NAME_MAPPING(ASMapViewImpl, "com.ashera.spatialkit", "AS")

@implementation ASMapViewImpl_MapViewExt

- (id<ASIWidget>)getWidget {
  return this$0_;
}

- (void)setMaxWidthWithInt:(int32_t)width {
  mMaxWidth_ = width;
}

- (void)setMaxHeightWithInt:(int32_t)height {
  mMaxHeight_ = height;
}

- (int32_t)getMaxWidth {
  return mMaxWidth_;
}

- (int32_t)getMaxHeight {
  return mMaxHeight_;
}

- (instancetype)initWithASMapViewImpl:(ASMapViewImpl *)outer$ {
  ASMapViewImpl_MapViewExt_initWithASMapViewImpl_(self, outer$);
  return self;
}

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec {
  if (mMaxWidth_ > 0) {
    widthMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxWidth_, ADView_MeasureSpec_AT_MOST);
  }
  if (mMaxHeight_ > 0) {
    heightMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxHeight_, ADView_MeasureSpec_AT_MOST);
  }
  [super onMeasureWithInt:widthMeasureSpec withInt:heightMeasureSpec];
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setWidthWithInt:[self getMeasuredWidth]];
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setHeightWithInt:[self getMeasuredHeight]];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, measureFinished) withASWidgetEvent:measureFinished_];
  }
}

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b {
  [super onLayoutWithBoolean:changed withInt:l withInt:t withInt:r withInt:b];
  ASViewImpl_setDrawableBoundsWithASIWidget_withInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  if (![self isOverlay]) {
    ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], l, t, r, b);
    ASMapViewImpl_nativeMakeFrameForChildWidgetWithInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  }
  [this$0_ replayBufferedEvents];
  ASViewImpl_redrawDrawablesWithASIWidget_(this$0_);
  overlays_ = ASViewImpl_drawOverlayWithASIWidget_withJavaUtilList_(this$0_, overlays_);
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setBWithInt:b];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setLWithInt:l];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setRWithInt:r];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setTWithInt:t];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setChangedWithBoolean:changed];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, onLayout) withASWidgetEvent:onLayoutEvent_];
  }
  if ([this$0_ isInvalidateOnFrameChange] && [this$0_ isInitialised]) {
    [this$0_ invalidate];
  }
}

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas {
}

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height {
  [self setMeasuredDimensionWithInt:width withInt:height];
}

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<JavaUtilList>)getMethods {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)initialized {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)drawableStateChanged {
  [super drawableStateChanged];
  if (![this$0_ isWidgetDisposed]) {
    ASViewImpl_drawableStateChangedWithASIWidget_(this$0_);
  }
}

- (ADView *)inflateViewWithNSString:(NSString *)layout {
  if (templates_ == nil) {
    templates_ = new_JavaUtilHashMap_init();
  }
  id<ASIWidget> template_ = [templates_ getWithId:layout];
  if (template_ == nil) {
    template_ = (id<ASIWidget>) cast_check([this$0_ quickConvertWithId:layout withNSString:@"template"], ASIWidget_class_());
    (void) [((id<JavaUtilMap>) nil_chk(templates_)) putWithId:layout withId:template_];
  }
  id<ASIWidget> widget = [((id<ASIWidget>) nil_chk(template_)) loadLazyWidgetsWithASHasWidgets:[this$0_ getParent]];
  return (ADView *) cast_chk([((id<ASIWidget>) nil_chk(widget)) asWidget], [ADView class]);
}

- (void)remeasure {
  if ([this$0_ getFragment] != nil) {
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
}

- (void)removeFromParent {
  [((id<ASHasWidgets>) nil_chk([this$0_ getParent])) removeWithASIWidget:this$0_];
}

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation {
  *IOSIntArray_GetRef(nil_chk(appScreenLocation), 0) = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  *IOSIntArray_GetRef(appScreenLocation, 1) = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
}

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame {
  ((ADRect *) nil_chk(displayFrame))->left_ = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->top_ = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->right_ = displayFrame->left_ + [self getWidth];
  displayFrame->bottom_ = displayFrame->top_ + [self getHeight];
}

- (void)offsetTopAndBottomWithInt:(int32_t)offset {
  [super offsetTopAndBottomWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)offsetLeftAndRightWithInt:(int32_t)offset {
  [super offsetLeftAndRightWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value {
  if ([((NSString *) nil_chk(name)) isEqual:@"state0"]) {
    [self setState0WithId:value];
    return;
  }
  if ([name isEqual:@"state1"]) {
    [self setState1WithId:value];
    return;
  }
  if ([name isEqual:@"state2"]) {
    [self setState2WithId:value];
    return;
  }
  if ([name isEqual:@"state3"]) {
    [self setState3WithId:value];
    return;
  }
  if ([name isEqual:@"state4"]) {
    [self setState4WithId:value];
    return;
  }
  [this$0_ setAttributeWithNSString:name withId:value withBoolean:!([value isKindOfClass:[NSString class]])];
}

- (void)setVisibilityWithInt:(int32_t)visibility {
  [super setVisibilityWithInt:visibility];
  ASViewImpl_nativeSetVisibilityWithId_withBoolean_([this$0_ asNativeWidget], visibility != ADView_VISIBLE);
}

- (void)setState0WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 0, value);
}

- (void)setState1WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 1, value);
}

- (void)setState2WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 2, value);
}

- (void)setState3WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 3, value);
}

- (void)setState4WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 4, value);
}

- (void)state0 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 0);
}

- (void)state1 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 1);
}

- (void)state2 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 2);
}

- (void)state3 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 3);
}

- (void)state4 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 4);
}

- (void)stateYes {
  ASViewImpl_stateYesWithASIWidget_(this$0_);
}

- (void)stateNo {
  ASViewImpl_stateNoWithASIWidget_(this$0_);
}

- (void)__javaClone:(ASMapViewImpl_MapViewExt *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 5, -1, -1, -1, -1 },
    { NULL, "LASILifeCycleDecorator;", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 15, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LADView;", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 22, 23, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 29, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 31, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 32, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 33, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 34, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getWidget);
  methods[1].selector = @selector(setMaxWidthWithInt:);
  methods[2].selector = @selector(setMaxHeightWithInt:);
  methods[3].selector = @selector(getMaxWidth);
  methods[4].selector = @selector(getMaxHeight);
  methods[5].selector = @selector(initWithASMapViewImpl:);
  methods[6].selector = @selector(onMeasureWithInt:withInt:);
  methods[7].selector = @selector(onLayoutWithBoolean:withInt:withInt:withInt:withInt:);
  methods[8].selector = @selector(executeWithNSString:withNSObjectArray:);
  methods[9].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[10].selector = @selector(newInstanceWithASIWidget:);
  methods[11].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:);
  methods[12].selector = @selector(getMethods);
  methods[13].selector = @selector(initialized);
  methods[14].selector = @selector(getAttributeWithASWidgetAttribute:);
  methods[15].selector = @selector(drawableStateChanged);
  methods[16].selector = @selector(inflateViewWithNSString:);
  methods[17].selector = @selector(remeasure);
  methods[18].selector = @selector(removeFromParent);
  methods[19].selector = @selector(getLocationOnScreenWithIntArray:);
  methods[20].selector = @selector(getWindowVisibleDisplayFrameWithADRect:);
  methods[21].selector = @selector(offsetTopAndBottomWithInt:);
  methods[22].selector = @selector(offsetLeftAndRightWithInt:);
  methods[23].selector = @selector(setMyAttributeWithNSString:withId:);
  methods[24].selector = @selector(setVisibilityWithInt:);
  methods[25].selector = @selector(setState0WithId:);
  methods[26].selector = @selector(setState1WithId:);
  methods[27].selector = @selector(setState2WithId:);
  methods[28].selector = @selector(setState3WithId:);
  methods[29].selector = @selector(setState4WithId:);
  methods[30].selector = @selector(state0);
  methods[31].selector = @selector(state1);
  methods[32].selector = @selector(state2);
  methods[33].selector = @selector(state3);
  methods[34].selector = @selector(state4);
  methods[35].selector = @selector(stateYes);
  methods[36].selector = @selector(stateNo);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASMapViewImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "measureFinished_", "LASMeasureEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onLayoutEvent_", "LASOnLayoutEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "overlays_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 35, -1 },
    { "mMaxWidth_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxHeight_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "templates_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 36, -1 },
  };
  static const void *ptrTable[] = { "setMaxWidth", "I", "setMaxHeight", "LASMapViewImpl;", "onMeasure", "II", "onLayout", "ZIIII", "execute", "LNSString;[LNSObject;", "updateMeasuredDimension", "newInstance", "LASIWidget;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;", "()Ljava/util/List<Ljava/lang/String;>;", "getAttribute", "LASWidgetAttribute;", "inflateView", "LNSString;", "getLocationOnScreen", "[I", "getWindowVisibleDisplayFrame", "LADRect;", "offsetTopAndBottom", "offsetLeftAndRight", "setMyAttribute", "LNSString;LNSObject;", "setVisibility", "setState0", "LNSObject;", "setState1", "setState2", "setState3", "setState4", "Ljava/util/List<Lcom/ashera/widget/IWidget;>;", "Ljava/util/Map<Ljava/lang/String;Lcom/ashera/widget/IWidget;>;" };
  static const J2ObjcClassInfo _ASMapViewImpl_MapViewExt = { "MapViewExt", "com.ashera.spatialkit", ptrTable, methods, fields, 7, 0x1, 37, 7, 3, -1, -1, -1, -1 };
  return &_ASMapViewImpl_MapViewExt;
}

@end

void ASMapViewImpl_MapViewExt_initWithASMapViewImpl_(ASMapViewImpl_MapViewExt *self, ASMapViewImpl *outer$) {
  self->this$0_ = outer$;
  ASMapView_init(self);
  self->measureFinished_ = new_ASMeasureEvent_init();
  self->onLayoutEvent_ = new_ASOnLayoutEvent_init();
  self->mMaxWidth_ = -1;
  self->mMaxHeight_ = -1;
}

ASMapViewImpl_MapViewExt *new_ASMapViewImpl_MapViewExt_initWithASMapViewImpl_(ASMapViewImpl *outer$) {
  J2OBJC_NEW_IMPL(ASMapViewImpl_MapViewExt, initWithASMapViewImpl_, outer$)
}

ASMapViewImpl_MapViewExt *create_ASMapViewImpl_MapViewExt_initWithASMapViewImpl_(ASMapViewImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASMapViewImpl_MapViewExt, initWithASMapViewImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASMapViewImpl_MapViewExt)

@implementation ASMapViewImpl_MapLibreMap

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASMapViewImpl_MapLibreMap_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LASMapViewImpl;", "LASMapViewImpl_MapLibreMap_OnMapClickListener;" };
  static const J2ObjcClassInfo _ASMapViewImpl_MapLibreMap = { "MapLibreMap", "com.ashera.spatialkit", ptrTable, methods, NULL, 7, 0x18, 1, 0, 0, 1, -1, -1, -1 };
  return &_ASMapViewImpl_MapLibreMap;
}

@end

void ASMapViewImpl_MapLibreMap_init(ASMapViewImpl_MapLibreMap *self) {
  NSObject_init(self);
}

ASMapViewImpl_MapLibreMap *new_ASMapViewImpl_MapLibreMap_init() {
  J2OBJC_NEW_IMPL(ASMapViewImpl_MapLibreMap, init)
}

ASMapViewImpl_MapLibreMap *create_ASMapViewImpl_MapLibreMap_init() {
  J2OBJC_CREATE_IMPL(ASMapViewImpl_MapLibreMap, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASMapViewImpl_MapLibreMap)

@implementation ASMapViewImpl_MapLibreMap_OnMapClickListener

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "Z", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(onMapClickWithASMapViewImpl_LatLng:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "onMapClick", "LASMapViewImpl_LatLng;", "LASMapViewImpl_MapLibreMap;" };
  static const J2ObjcClassInfo _ASMapViewImpl_MapLibreMap_OnMapClickListener = { "OnMapClickListener", "com.ashera.spatialkit", ptrTable, methods, NULL, 7, 0x608, 1, 0, 2, -1, -1, -1, -1 };
  return &_ASMapViewImpl_MapLibreMap_OnMapClickListener;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ASMapViewImpl_MapLibreMap_OnMapClickListener)

@implementation ASMapViewImpl_LatLng

- (instancetype)initWithASMapViewImpl:(ASMapViewImpl *)outer$
                           withDouble:(double)lat
                           withDouble:(double)lng {
  ASMapViewImpl_LatLng_initWithASMapViewImpl_withDouble_withDouble_(self, outer$, lat, lng);
  return self;
}

- (double)getLatitude {
  return lat_;
}

- (double)getLongitude {
  return lng_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "D", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "D", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASMapViewImpl:withDouble:withDouble:);
  methods[1].selector = @selector(getLatitude);
  methods[2].selector = @selector(getLongitude);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "lat_", "D", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "lng_", "D", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASMapViewImpl;DD", "LASMapViewImpl;" };
  static const J2ObjcClassInfo _ASMapViewImpl_LatLng = { "LatLng", "com.ashera.spatialkit", ptrTable, methods, fields, 7, 0x0, 3, 2, 1, -1, -1, -1, -1 };
  return &_ASMapViewImpl_LatLng;
}

@end

void ASMapViewImpl_LatLng_initWithASMapViewImpl_withDouble_withDouble_(ASMapViewImpl_LatLng *self, ASMapViewImpl *outer$, double lat, double lng) {
  NSObject_init(self);
  self->lat_ = lat;
  self->lng_ = lng;
}

ASMapViewImpl_LatLng *new_ASMapViewImpl_LatLng_initWithASMapViewImpl_withDouble_withDouble_(ASMapViewImpl *outer$, double lat, double lng) {
  J2OBJC_NEW_IMPL(ASMapViewImpl_LatLng, initWithASMapViewImpl_withDouble_withDouble_, outer$, lat, lng)
}

ASMapViewImpl_LatLng *create_ASMapViewImpl_LatLng_initWithASMapViewImpl_withDouble_withDouble_(ASMapViewImpl *outer$, double lat, double lng) {
  J2OBJC_CREATE_IMPL(ASMapViewImpl_LatLng, initWithASMapViewImpl_withDouble_withDouble_, outer$, lat, lng)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASMapViewImpl_LatLng)

@implementation ASMapViewImpl_OnMapClickListener

- (NSString *)getAction {
  return action_;
}

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue {
  ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_(self, w, strValue);
  return self;
}

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue
                     withNSString:(NSString *)action {
  ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_withNSString_(self, w, strValue, action);
  return self;
}

- (bool)onMapClickWithASMapViewImpl_LatLng:(ASMapViewImpl_LatLng *)point {
  bool result = true;
  if (action_ == nil || [action_ isEqual:@"onMapClick"]) {
    [((id<ASIWidget>) nil_chk(w_)) syncModelFromUiToPojoWithNSString:@"onMapClick"];
    id<JavaUtilMap> obj = [self getOnMapClickEventObjWithASMapViewImpl_LatLng:point];
    NSString *commandName = (NSString *) cast_chk([((id<JavaUtilMap>) nil_chk(obj)) getWithId:ASEventExpressionParser_KEY_COMMAND_NAME], [NSString class]);
    NSString *commandType = (NSString *) cast_chk([obj getWithId:ASEventExpressionParser_KEY_COMMAND_TYPE], [NSString class]);
    switch (JreIndexOfStr(commandType, (id[]){ @"+" }, 1)) {
      case 0:
      if (ASEventCommandFactory_hasCommandWithNSString_(commandName)) {
        id commandResult = [((id<ASEventCommand>) nil_chk(ASEventCommandFactory_getCommandWithNSString_(commandName))) executeCommandWithASIWidget:w_ withJavaUtilMap:obj withNSObjectArray:[IOSObjectArray newArrayWithObjects:(id[]){ point } count:1 type:NSObject_class_()]];
        if (commandResult != nil) {
          result = [(JavaLangBoolean *) cast_chk(commandResult, [JavaLangBoolean class]) booleanValue];
        }
      }
      break;
      default:
      break;
    }
    if ([obj containsKeyWithId:@"refreshUiFromModel"]) {
      id widgets = [obj removeWithId:@"refreshUiFromModel"];
      ASViewImpl_refreshUiFromModelWithASIWidget_withId_withBoolean_(w_, widgets, true);
    }
    if ([((id<ASIWidget>) nil_chk(w_)) getModelUiToPojoEventIds] != nil) {
      ASViewImpl_refreshUiFromModelWithASIWidget_withId_withBoolean_(w_, [((id<ASIWidget>) nil_chk(w_)) getModelUiToPojoEventIds], true);
    }
    if (strValue_ != nil && ![strValue_ isEmpty] && ![((NSString *) nil_chk([((NSString *) nil_chk(strValue_)) java_trim])) java_hasPrefix:@"+"]) {
      id<ASIActivity> activity = [((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getRootActivity];
      if (activity != nil) {
        [activity sendEventMessageWithJavaUtilMap:obj];
      }
    }
  }
  return result;
}

- (id<JavaUtilMap>)getOnMapClickEventObjWithASMapViewImpl_LatLng:(ASMapViewImpl_LatLng *)point {
  id<JavaUtilMap> obj = ASPluginInvoker_getJSONCompatMap();
  (void) [((id<JavaUtilMap>) nil_chk(obj)) putWithId:@"action" withId:@"action"];
  (void) [obj putWithId:@"eventType" withId:@"mapclick"];
  (void) [obj putWithId:@"fragmentId" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getFragmentId]];
  (void) [obj putWithId:@"actionUrl" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getActionUrl]];
  (void) [obj putWithId:@"namespace" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getNamespace]];
  if ([((id<ASIWidget>) nil_chk(w_)) getComponentId] != nil) {
    (void) [obj putWithId:@"componentId" withId:[((id<ASIWidget>) nil_chk(w_)) getComponentId]];
  }
  ASPluginInvoker_putJSONSafeObjectIntoMapWithJavaUtilMap_withNSString_withId_(obj, @"id", [((id<ASIWidget>) nil_chk(w_)) getId]);
  ASMapViewImpl_addEventInfoWithJavaUtilMap_withASMapViewImpl_LatLng_(obj, point);
  (void) ASEventExpressionParser_parseEventExpressionWithNSString_withJavaUtilMap_(strValue_, obj);
  [((id<ASIWidget>) nil_chk(w_)) updateModelToEventMapWithJavaUtilMap:obj withNSString:@"onMapClick" withNSString:(NSString *) cast_chk([obj getWithId:ASEventExpressionParser_KEY_EVENT_ARGS], [NSString class])];
  return obj;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, 4, 3, -1, 5, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getAction);
  methods[1].selector = @selector(initWithASIWidget:withNSString:);
  methods[2].selector = @selector(initWithASIWidget:withNSString:withNSString:);
  methods[3].selector = @selector(onMapClickWithASMapViewImpl_LatLng:);
  methods[4].selector = @selector(getOnMapClickEventObjWithASMapViewImpl_LatLng:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "w_", "LASIWidget;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "view_", "LADView;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "strValue_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "action_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASIWidget;LNSString;", "LASIWidget;LNSString;LNSString;", "onMapClick", "LASMapViewImpl_LatLng;", "getOnMapClickEventObj", "(Lcom/ashera/spatialkit/MapViewImpl$LatLng;)Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;", "LASMapViewImpl;" };
  static const J2ObjcClassInfo _ASMapViewImpl_OnMapClickListener = { "OnMapClickListener", "com.ashera.spatialkit", ptrTable, methods, fields, 7, 0xa, 5, 4, 6, -1, -1, -1, -1 };
  return &_ASMapViewImpl_OnMapClickListener;
}

@end

void ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_(ASMapViewImpl_OnMapClickListener *self, id<ASIWidget> w, NSString *strValue) {
  NSObject_init(self);
  self->w_ = w;
  self->strValue_ = strValue;
}

ASMapViewImpl_OnMapClickListener *new_ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue) {
  J2OBJC_NEW_IMPL(ASMapViewImpl_OnMapClickListener, initWithASIWidget_withNSString_, w, strValue)
}

ASMapViewImpl_OnMapClickListener *create_ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue) {
  J2OBJC_CREATE_IMPL(ASMapViewImpl_OnMapClickListener, initWithASIWidget_withNSString_, w, strValue)
}

void ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_withNSString_(ASMapViewImpl_OnMapClickListener *self, id<ASIWidget> w, NSString *strValue, NSString *action) {
  NSObject_init(self);
  self->w_ = w;
  self->strValue_ = strValue;
  self->action_ = action;
}

ASMapViewImpl_OnMapClickListener *new_ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action) {
  J2OBJC_NEW_IMPL(ASMapViewImpl_OnMapClickListener, initWithASIWidget_withNSString_withNSString_, w, strValue, action)
}

ASMapViewImpl_OnMapClickListener *create_ASMapViewImpl_OnMapClickListener_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action) {
  J2OBJC_CREATE_IMPL(ASMapViewImpl_OnMapClickListener, initWithASIWidget_withNSString_withNSString_, w, strValue, action)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASMapViewImpl_OnMapClickListener)

@implementation ASMapViewImpl_MapViewDelloc

- (instancetype)initWithASMapViewImpl:(ASMapViewImpl *)outer$ {
  ASMapViewImpl_MapViewDelloc_initWithASMapViewImpl_(self, outer$);
  return self;
}

- (void)run {
  ASMapViewImpl_releaseMLNMapView(this$0_);
}

- (void)__javaClone:(ASMapViewImpl_MapViewDelloc *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASMapViewImpl:);
  methods[1].selector = @selector(run);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASMapViewImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASMapViewImpl;" };
  static const J2ObjcClassInfo _ASMapViewImpl_MapViewDelloc = { "MapViewDelloc", "com.ashera.spatialkit", ptrTable, methods, fields, 7, 0x12, 2, 1, 0, -1, -1, -1, -1 };
  return &_ASMapViewImpl_MapViewDelloc;
}

@end

void ASMapViewImpl_MapViewDelloc_initWithASMapViewImpl_(ASMapViewImpl_MapViewDelloc *self, ASMapViewImpl *outer$) {
  self->this$0_ = outer$;
  NSObject_init(self);
}

ASMapViewImpl_MapViewDelloc *new_ASMapViewImpl_MapViewDelloc_initWithASMapViewImpl_(ASMapViewImpl *outer$) {
  J2OBJC_NEW_IMPL(ASMapViewImpl_MapViewDelloc, initWithASMapViewImpl_, outer$)
}

ASMapViewImpl_MapViewDelloc *create_ASMapViewImpl_MapViewDelloc_initWithASMapViewImpl_(ASMapViewImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASMapViewImpl_MapViewDelloc, initWithASMapViewImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASMapViewImpl_MapViewDelloc)
