//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\org\maplibre\android\maps\MapView.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_MapView")
#ifdef RESTRICT_MapView
#define INCLUDE_ALL_MapView 0
#else
#define INCLUDE_ALL_MapView 1
#endif
#undef RESTRICT_MapView

#if !defined (ASMapView_) && (INCLUDE_ALL_MapView || defined(INCLUDE_ASMapView))
#define ASMapView_

#define RESTRICT_FrameLayout 1
#define INCLUDE_ADFrameLayout 1
#include "FrameLayout.h"

@interface ASMapView : ADFrameLayout

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMapView)

FOUNDATION_EXPORT void ASMapView_init(ASMapView *self);

FOUNDATION_EXPORT ASMapView *new_ASMapView_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMapView *create_ASMapView_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMapView)

@compatibility_alias OrgMaplibreAndroidMapsMapView ASMapView;


#endif

#pragma pop_macro("INCLUDE_ALL_MapView")
