//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\com\ashera\spatialkit\SpatialKitPlugin.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "CompassManager.h"
#include "CompassViewImpl.h"
#include "FragmentManagerFactory.h"
#include "J2ObjC_source.h"
#include "MapViewImpl.h"
#include "SpatialKitPlugin.h"
#include "WidgetFactory.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@implementation ASSpatialKitPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASSpatialKitPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASSpatialKitPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASSpatialKitPlugin = { "SpatialKitPlugin", "com.ashera.spatialkit", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASSpatialKitPlugin;
}

@end

void ASSpatialKitPlugin_init(ASSpatialKitPlugin *self) {
  NSObject_init(self);
}

ASSpatialKitPlugin *new_ASSpatialKitPlugin_init() {
  J2OBJC_NEW_IMPL(ASSpatialKitPlugin, init)
}

ASSpatialKitPlugin *create_ASSpatialKitPlugin_init() {
  J2OBJC_CREATE_IMPL(ASSpatialKitPlugin, init)
}

void ASSpatialKitPlugin_initPlugin() {
  ASSpatialKitPlugin_initialize();
  ASWidgetFactory_registerAttributableForWithNSString_withASIAttributable_(@"View", new_ASCompassViewImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASMapViewImpl_init());
  ASFragmentManagerFactory_registerManagerWithNSString_withASIFragmentManager_(@"compass", new_ASCompassManager_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASSpatialKitPlugin)

J2OBJC_NAME_MAPPING(ASSpatialKitPlugin, "com.ashera.spatialkit", "AS")
