//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\com\ashera\spatialkit\SpatialKitPlugin.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SpatialKitPlugin")
#ifdef RESTRICT_SpatialKitPlugin
#define INCLUDE_ALL_SpatialKitPlugin 0
#else
#define INCLUDE_ALL_SpatialKitPlugin 1
#endif
#undef RESTRICT_SpatialKitPlugin

#if !defined (ASSpatialKitPlugin_) && (INCLUDE_ALL_SpatialKitPlugin || defined(INCLUDE_ASSpatialKitPlugin))
#define ASSpatialKitPlugin_

@interface ASSpatialKitPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSpatialKitPlugin)

FOUNDATION_EXPORT void ASSpatialKitPlugin_init(ASSpatialKitPlugin *self);

FOUNDATION_EXPORT ASSpatialKitPlugin *new_ASSpatialKitPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSpatialKitPlugin *create_ASSpatialKitPlugin_init(void);

FOUNDATION_EXPORT void ASSpatialKitPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASSpatialKitPlugin)

@compatibility_alias ComAsheraSpatialkitSpatialKitPlugin ASSpatialKitPlugin;


#endif

#pragma pop_macro("INCLUDE_ALL_SpatialKitPlugin")
