//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSpatialKitPlugin\src\main\java\com\ashera\spatialkit\TSAGeoMag.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TSAGeoMag")
#ifdef RESTRICT_TSAGeoMag
#define INCLUDE_ALL_TSAGeoMag 0
#else
#define INCLUDE_ALL_TSAGeoMag 1
#endif
#undef RESTRICT_TSAGeoMag

#if !defined (ASTSAGeoMag_) && (INCLUDE_ALL_TSAGeoMag || defined(INCLUDE_ASTSAGeoMag))
#define ASTSAGeoMag_

@class JavaLangDouble;
@class JavaUtilGregorianCalendar;

/*!
 @brief <p>
   Last updated on Jan 6, 2020</p><p>
   <b>NOTE: </b>Comment out the logger references, and put back in the System.out.println 
      statements if not using log4j in your application.
 Checks are not made on the method inputs
      to ensure they are within a valid range.</p><p>
      
 	Verified by a JUnit test using the test values distributed with the 2020 epoch update.</p><p>
   
 	This is a class to generate the magnetic declination,
 	magnetic field strength and inclination for any point
 	on the earth.  The true bearing = magnetic bearing + declination.
  	This class is adapted from an Applet from the NOAA National Data Center
 	at <a href="http://www.ngdc.noaa.gov/seg/segd.shtml"> http://www.ngdc.noaa.gov/seg/segd.shtml.</a>
  	None of the calculations
 	were changed.  This class requires an input file named WMM.COF, which
 	must be in the same directory that the application is run from. <br> 
 	<b>NOTE:</b> If the WMM.COF file is missing, the internal fit coefficients
 	for 2020 will be used.
 	Using the correct date, the declination is accurate to about 0.5 degrees.</p><p>
   This is the LANL D-3 version of the GeoMagnetic calculator from
 	the NOAA National Data Center at http://www.ngdc.noaa.gov/seg/segd.shtml.</p><p>
 	
 	Adapted by John St. Ledger, Los Alamos National Laboratory
 	June 25, 1999</p><p>
 	Version 2 Comments:  The world magnetic model is updated every 5 years.
 	The data for 2000 uses the same algorithm to calculate the magnetic
 	field variables.  The only change is in the spherical harmonic coefficients
 	in the input file.  The input file has been renamed to WMM.COF.  Once again,
 	the date was fixed.  This time to January 1, 2001.  Also, a deprecated
 	constructor for StreamTokenizer was replaced, and the error messages in the catch
 	clause were changed.  Methods to get the field strength and inclination
 	were added.</p><p>
 	Found out some interesting information about the altitude. The altitude entered 
       for the calculations is the height above the WGS84 spheroid, not height MSL. Using
       MSL height means that the altitude could be in error by as much as 200 meters.
       This should not be significant for our applications.</p>
             
 <p><b>NOTE:</b> This class is not thread safe.</p>
 @version 3.0 January 19, 2000
 	<p>Updated for 2000 data.</p>
 @version 4.0 March 1, 2002
 	<p>Changed so that if data file doesn't exist,
 	it uses an internal version of the coefficients from
 	the 2000 update.</p>
 @version 5.0 June 1, 2005
 	<p>Changed so that if data file doesn't exist,
 	it uses an internal version of the coefficients from
 	the 2005 update.  Previously, only calculated the declination at sea level
 	for one date.  Now can return all of the variables as a function of date and
 	altitude.  Original version used float variables.  All changed to type double.
 	Does not check if the input date is within the valid block.</p>
 @version 5.1 June 20, 2005
 	<p>Fixed a bug discovered by Alvin Liem.  In my zeal to clean up compiler comments
 	I deleted some double casts for integers that resulted in an integer division
 	being made when double division was needed.</p>
 @version 5.2  June 1, 2006  
 <p>Took out the input error variable, which was no longer being used.
   Now verified with a JUnit test.  Deleted the main() method which printed
   a table of test values.</p>
 @version 5.3  January 28, 2009  
 <p>Fixed JavaDoc comments, and replaced the StringTokenizer uses with String.split().
 @version 5.4 January 5, 2010
   <p>Updated for 2010 data. The new 2010 WMM.COF values are now used. Also, added 
   <a href="http://logging.apache.org/log4j/1.2/"> log4j</a> support.</p>
 @version 5.5 October 10, 2012
   <p>Made minor changes. The default date used when the caller does not input a date is now the epoch + 2.5 years,
      rather than being a fixed value. This means that the default date is automatically updated if a new WMM.COF file
      is used. Also, now have a method to return the date as a decimal year, given the Gregorian Calendar date.</p>
 @version 5.6 January 15, 2015
   <p>Updated the internal coefficients to the 2015 values. Passes the new JUnit tests.</p>
 @version 5.7 May 26, 2015
   <p>Martin Frassl discovered a major bug in the code. I thought that X was in the East direction. It is not. The X axis
      is in the North direction. This is now fixed so that getNorthIntensity and getEastIntensity return the correct values.
      Thank you Martin!. The X, Y, and Z axes are defined in table 1 of the reference:</p>
      <ul>Reference:
      <li>Chulliat, A., S. Macmillan, P. Alken, C. Beggan, M. Nair, B. Hamilton, A. Woods, V. Ridley, S. Maus and A. Thomson, 
      2015, The US/UK World Magnetic Model for 2015-2020: Technical Report, National Geophysical Data Center, NOAA. 
      doi: 10.7289/V5TB14V7</li></ul>
 @version 5.8 April 11, 2019
   <p> Updated to use the 2018 update to the 2015 epoch coefficients.
 @version 5.9 January 6, 2020
   <p>Updated the internal coefficients to the 2020 epoch values. Passes the new JUnit tests.</p>
        
 </li></ul>
      <ul>References:
        <li>JOHN M. QUINN, DAVID J. KERRIDGE AND DAVID R. BARRACLOUGH,
             WORLD MAGNETIC CHARTS FOR 1985 - SPHERICAL HARMONIC
             MODELS OF THE GEOMAGNETIC FIELD AND ITS SECULAR
             VARIATION, GEOPHYS. J. R. ASTR. SOC. (1986) 87,
             PP 1143-1157</li>
        <li>DEFENSE MAPPING AGENCY TECHNICAL REPORT, TR 8350.2:
             DEPARTMENT OF DEFENSE WORLD GEODETIC SYSTEM 1984,
             SEPT. 30 (1987)</li>
        <li>JOSEPH C. CAIN, ET AL.; A PROPOSED MODEL FOR THE
             INTERNATIONAL GEOMAGNETIC REFERENCE FIELD - 1965,
             J. GEOMAG. AND GEOELECT. VOL. 19, NO. 4, PP 335-355
             (1967) (SEE APPENDIX)</li>
        <li>ALFRED J. ZMUDA, WORLD MAGNETIC SURVEY 1957-1969,
             INTERNATIONAL ASSOCIATION OF GEOMAGNETISM AND
             AERONOMY (IAGA) BULLETIN #28, PP 186-188 (1971)</li>
        <li>JOHN M. QUINN, RACHEL J. COLEMAN, MICHAEL R. PECK, AND
             STEPHEN E. LAUBER; THE JOINT US/UK 1990 EPOCH
             WORLD MAGNETIC MODEL, TECHNICAL REPORT NO. 304,
             NAVAL OCEANOGRAPHIC OFFICE (1991)</li>
        <li>JOHN M. QUINN, RACHEL J. COLEMAN, DONALD L. SHIEL, AND
             JOHN M. NIGRO; THE JOINT US/UK 1995 EPOCH WORLD
             MAGNETIC MODEL, TECHNICAL REPORT NO. 314, NAVAL
             OCEANOGRAPHIC OFFICE (1995)</li></ul>
      <p>WMM-2000 is a National Imagery and Mapping Agency (NIMA) standard 
      product. It is covered under NIMA Military Specification: 
      MIL-W-89500 (1993).
      For information on the use and applicability of this product contact</p>
                      DIRECTOR<br>
                      NATIONAL IMAGERY AND MAPPING AGENCY/HEADQUARTERS<br>
                      ATTN: CODE P33<br>
                      12310 SUNRISE VALLEY DRIVE<br>
                      RESTON, VA 20191-3449<br>
                      (703) 264-3002<br>
      <p>The FORTRAN version of GEOMAG PROGRAMMED BY:</p>
                      JOHN M. QUINN  7/19/90<br>
                      FLEET PRODUCTS DIVISION, CODE N342<br>
                      NAVAL OCEANOGRAPHIC OFFICE (NAVOCEANO)<br>
                      STENNIS SPACE CENTER (SSC), MS 39522-5001<br>
                      USA<br>
                      PHONE:   COM:  (601) 688-5828<br>
                                AV:        485-5828<br>
                               FAX:  (601) 688-5521<br>
      <p>NOW AT:</p>
                      GEOMAGNETICS GROUP<br>
                      U. S. GEOLOGICAL SURVEY   MS 966<br>
                      FEDERAL CENTER<br>
                      DENVER, CO   80225-0046<br>
                      USA<br>
                      PHONE:   COM: (303) 273-8475<br>
                               FAX: (303) 273-8600<br>
                      EMAIL:   quinn@@ghtmail.cr.usgs.gov<br>
 */
@interface ASTSAGeoMag : NSObject

#pragma mark Public

/*!
 @brief Instantiates object by calling initModel().
 */
- (instancetype)init;

/*!
 @brief <p>  
    Given a Gregorian Calendar object, this returns the decimal year
    value for the calendar, accurate to the day of the input calendar.
 The hours, minutes, and seconds of the date are ignored.</p><p>
    
    If the input Gregorian Calendar is new GregorianCalendar(2012, 6, 1), all of
    the first of July is counted, and this returns 2012.5. (183 days out of 366)</p><p>
    
    If the input Gregorian Calendar is new GregorianCalendar(2010, 0, 0), the first
    of January is not counted, and this returns 2010.0</p><p>
 @param cal Has the date (year, month, and day of the month)
 @return The date in decimal years
 */
- (double)decimalYearWithJavaUtilGregorianCalendar:(JavaUtilGregorianCalendar *)cal;

/*!
 @brief Returns the declination from the Department of
 	Defense geomagnetic model and data, in degrees.The
 	magnetic heading + declination = true heading.
 The date and
   altitude are the defaults, of half way through the valid 
   5 year period, and 0 elevation.
  	(True heading + variation = magnetic heading.)
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @return The declination in degrees.
 */
- (double)getDeclinationWithDouble:(double)dlat
                        withDouble:(double)dlong;

/*!
 @brief Returns the declination from the Department of
 	Defense geomagnetic model and data, in degrees.The
 	magnetic heading + declination = true heading.
 (True heading + variation = magnetic heading.)
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @param year The date as a decimal year.
 @param altitude The altitude in kilometers.
 @return The declination in degrees.
 */
- (double)getDeclinationWithDouble:(double)dlat
                        withDouble:(double)dlong
                        withDouble:(double)year
                        withDouble:(double)altitude;

/*!
 @brief Returns the magnetic field dip angle from the
 	Department of Defense geomagnetic model and data,
 	in degrees.The date and
   altitude are the defaults, of half way through the valid 
   5 year period, and 0 elevation.
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @return The magnetic field dip angle, in degrees.
 */
- (double)getDipAngleWithDouble:(double)dlat
                     withDouble:(double)dlong;

/*!
 @brief Returns the magnetic field dip angle from the
 	Department of Defense geomagnetic model and data,
 	in degrees.
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @param year Date of the calculation in decimal years.
 @param altitude Altitude of the calculation in kilometers.
 @return The magnetic field dip angle, in degrees.
 */
- (double)getDipAngleWithDouble:(double)dlat
                     withDouble:(double)dlong
                     withDouble:(double)year
                     withDouble:(double)altitude;

/*!
 @brief Returns the easterly magnetic field intensity from the
 	Department of Defense geomagnetic model and data
 	in nano Tesla.The date and
   altitude are the defaults, of half way through the valid 
   5 year period, and 0 elevation.
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @return The easterly component of the magnetic field strength in nano Tesla.
 */
- (double)getEastIntensityWithDouble:(double)dlat
                          withDouble:(double)dlong;

/*!
 @brief Returns the easterly magnetic field intensity from the
 	Department of Defense geomagnetic model and data
 	in nano Tesla.
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @param year Date of the calculation in decimal years.
 @param altitude Altitude of the calculation in kilometers.
 @return The easterly component of the magnetic field strength in nano Tesla.
 */
- (double)getEastIntensityWithDouble:(double)dlat
                          withDouble:(double)dlong
                          withDouble:(double)year
                          withDouble:(double)altitude;

/*!
 @brief Returns the horizontal magnetic field intensity from the
 	Department of Defense geomagnetic model and data
 	in nano Tesla.The date and
   altitude are the defaults, of half way through the valid 
   5 year period, and 0 elevation.
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @return The horizontal magnetic field strength in nano Tesla.
 */
- (double)getHorizontalIntensityWithDouble:(double)dlat
                                withDouble:(double)dlong;

/*!
 @brief Returns the horizontal magnetic field intensity from the
 	Department of Defense geomagnetic model and data
 	in nano Tesla.
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @param year Date of the calculation in decimal years.
 @param altitude Altitude of the calculation in kilometers.
 @return The horizontal magnetic field strength in nano Tesla.
 */
- (double)getHorizontalIntensityWithDouble:(double)dlat
                                withDouble:(double)dlong
                                withDouble:(double)year
                                withDouble:(double)altitude;

/*!
 @brief Returns the magnetic field intensity from the
 	Department of Defense geomagnetic model and data
 	in nano Tesla.The date and
   altitude are the defaults, of half way through the valid 
   5 year period, and 0 elevation.
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @return Magnetic field strength in nano Tesla.
 */
- (double)getIntensityWithDouble:(double)dlat
                      withDouble:(double)dlong;

/*!
 @brief Returns the magnetic field intensity from the 
 	Department of Defense geomagnetic model and data
 	in nano Tesla.
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @param year Date of the calculation in decimal years.
 @param altitude Altitude of the calculation in kilometers.
 @return Magnetic field strength in nano Tesla.
 */
- (double)getIntensityWithDouble:(double)dlat
                      withDouble:(double)dlong
                      withDouble:(double)year
                      withDouble:(double)altitude;

/*!
 @brief Returns the northerly magnetic field intensity from the
 	Department of Defense geomagnetic model and data
 	in nano Tesla.The date and
   altitude are the defaults, of half way through the valid 
   5 year period, and 0 elevation.
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @return The northerly component of the magnetic field strength in nano Tesla.
 */
- (double)getNorthIntensityWithDouble:(double)dlat
                           withDouble:(double)dlong;

/*!
 @brief Returns the northerly magnetic field intensity from the
 	Department of Defense geomagnetic model and data
 	in nano Tesla.
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @param year Date of the calculation in decimal years.
 @param altitude Altitude of the calculation in kilometers.
 @return The northerly component of the magnetic field strength in nano Tesla.
 */
- (double)getNorthIntensityWithDouble:(double)dlat
                           withDouble:(double)dlong
                           withDouble:(double)year
                           withDouble:(double)altitude;

/*!
 @brief Returns the vertical magnetic field intensity from the
 	Department of Defense geomagnetic model and data
 	in nano Tesla.The date and
   altitude are the defaults, of half way through the valid 
   5 year period, and 0 elevation.
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @return The vertical magnetic field strength in nano Tesla.
 */
- (double)getVerticalIntensityWithDouble:(double)dlat
                              withDouble:(double)dlong;

/*!
 @brief Returns the vertical magnetic field intensity from the
 	Department of Defense geomagnetic model and data
 	in nano Tesla.
 @param dlat Latitude in decimal degrees.
 @param dlong Longitude in decimal degrees.
 @param year Date of the calculation in decimal years.
 @param altitude Altitude of the calculation in kilometers.
 @return The vertical magnetic field strength in nano Tesla.
 */
- (double)getVerticalIntensityWithDouble:(double)dlat
                              withDouble:(double)dlong
                              withDouble:(double)year
                              withDouble:(double)altitude;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTSAGeoMag)

FOUNDATION_EXPORT void ASTSAGeoMag_init(ASTSAGeoMag *self);

FOUNDATION_EXPORT ASTSAGeoMag *new_ASTSAGeoMag_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTSAGeoMag *create_ASTSAGeoMag_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTSAGeoMag)

@compatibility_alias ComAsheraSpatialkitTSAGeoMag ASTSAGeoMag;


#endif

#pragma pop_macro("INCLUDE_ALL_TSAGeoMag")
